- id: '1608366491394'
  alias: Motion-activated Light Hal
  description: ''
  use_blueprint:
    path: myown/motion_light_lightlevel.yaml
    input:
      motion_entity: binary_sensor.hal_occupancy
      light_target:
        entity_id: light.hal
      threshold_input: input_number.lightlevel
- id: '1608456934898'
  alias: Motion-activated Light Lightlevel traphal
  description: ''
  use_blueprint:
    path: myown/motion_light_lightlevel.yaml
    input:
      motion_entity: binary_sensor.traphal_occupancy
      threshold_input: input_number.lightlevel
      light_target:
        device_id: e837c327c3614cb3a4b06ec0087b6a43
- id: '1608456965094'
  alias: Motion-activated Light Lightlevel overloop
  description: ''
  use_blueprint:
    path: myown/motion_light_lightlevel.yaml
    input:
      motion_entity: binary_sensor.overloop_occupancy
      threshold_input: input_number.lightlevel
      light_target:
        device_id: b9ef9bd7da184d988ac72702f6cb2e8a
- id: '1608714195345'
  alias: aqara studeerkamer
  description: ''
  use_blueprint:
    path: myown/aqara_doubleswitch_action_light.yaml
    input:
      switch_entity: sensor.studeerkamer_action
      light_entity_left: light.computer
      light_entity_right: light.computer
      light_entity_both: light.computer
      mode_selector: input_select.house_mode
- id: '1608714470902'
  alias: aqara woonkamer
  description: ''
  use_blueprint:
    path: myown/aqara_doubleswitch_action_light.yaml
    input:
      switch_entity: sensor.switch_woonkamer_action
      light_entity_left: light.hue_lightstrip_plus_1
      light_entity_right: light.staande_lamp
      light_entity_both: light.woonkamer
      mode_selector: input_select.house_mode
- id: '1608714589824'
  alias: aqara slaapkamer
  description: ''
  use_blueprint:
    path: myown/aqara_doubleswitch_action_light.yaml
    input:
      switch_entity: sensor.slaapkamer_action
      light_entity_left: light.sk_spot
      light_entity_right: light.sk_ceiling
      light_entity_both: light.slaapkamer
      mode_selector: input_select.house_mode
- id: '1608714672968'
  alias: aqara keuken
  description: ''
  use_blueprint:
    path: myown/aqara_doubleswitch_action_light.yaml
    input:
      switch_entity: sensor.keuken_action
      light_entity_left: light.eetkamer
      light_entity_right: light.keuken
      light_entity_both: light.eetkamer, light.keuken
      mode_selector: input_select.house_mode
- id: '1610275729152'
  alias: Auto-verlaat-parkeerplaats
  description: ''
  trigger:
  - platform: device
    device_id: 7e3829df257c2775577967545c92c196
    domain: device_tracker
    entity_id: device_tracker.sz_436_p_device_tracker
    type: leaves
    zone: zone.parking
  condition:
  - condition: device
    device_id: 5783e9f6177e11eb9d775b4d6ed4f183
    domain: device_tracker
    entity_id: device_tracker.kb2003
    type: is_home
  action:
  - device_id: 5783e9f6177e11eb9d775b4d6ed4f183
    domain: mobile_app
    type: notify
    message: Auto verlaat de parkeerplaats
    title: ALARM!
  mode: single
- id: '1610285278747'
  alias: test-room-presence
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.oneplus_8t_room_presence
    to: Hal
  condition:
  - condition: device
    device_id: 5783e9f6177e11eb9d775b4d6ed4f183
    domain: device_tracker
    entity_id: device_tracker.kb2003
    type: is_not_home
  action:
  - service: notify.pushover
    data:
      title: room-presence testing
      message: kb2003 is in {{states('sensor.oneplus_8t_room_presence')}} en afstand
        is {{state_attr('sensor.oneplus_8t_room_presence','distance')}}
  mode: single
- id: '1646658068592'
  alias: test media play
  description: ''
  trigger:
  - platform: state
    entity_id: person.arnoud
    to: home
  condition:
  - condition: time
    after: 09:00:00
    before: '16:00:00'
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.speakers
    data:
      media_content_id: media-source://radio_browser/9513b20b-e4bd-11e8-a9cc-52543be04c81
      media_content_type: audio/mpeg
    metadata:
      title: Arrow Classic Rock
      thumbnail: https://www.arrow.nl/wp-content/themes/bones-master/library/images/apple-touch-icon.png
      media_class: music
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://radio_browser
      - media_content_type: music
        media_content_id: media-source://radio_browser/country/NL
  mode: single
