- id: '1608366491394'
  alias: Motion-activated Light Hal
  description: ''
  use_blueprint:
    path: myown/motion_light_lightlevel.yaml
    input:
      motion_entity: binary_sensor.hal_occupancy
      light_target:
        entity_id: light.hal
      threshold_input: input_number.lightlevel
- id: '1608456934898'
  alias: Motion-activated Light Lightlevel traphal
  description: ''
  use_blueprint:
    path: myown/motion_light_lightlevel.yaml
    input:
      motion_entity: binary_sensor.traphal_occupancy
      threshold_input: input_number.lightlevel
      light_target:
        device_id: e837c327c3614cb3a4b06ec0087b6a43
- id: '1608456965094'
  alias: Motion-activated Light Lightlevel overloop
  description: ''
  use_blueprint:
    path: myown/motion_light_lightlevel.yaml
    input:
      motion_entity: binary_sensor.overloop_occupancy
      threshold_input: input_number.lightlevel
      light_target:
        device_id: b9ef9bd7da184d988ac72702f6cb2e8a
- id: '1608714195345'
  alias: aqara studeerkamer
  description: ''
  use_blueprint:
    path: myown/aqara_doubleswitch_action_light.yaml
    input:
      switch_entity: sensor.studeerkamer_action
      light_entity_left: light.computer
      light_entity_right: light.computer
      light_entity_both: light.computer
      mode_selector: input_select.house_mode
- id: '1608714470902'
  alias: aqara woonkamer
  description: ''
  use_blueprint:
    path: myown/aqara_doubleswitch_action_light.yaml
    input:
      switch_entity: sensor.woonkamer_action
      light_entity_left: light.hue_lightstrip_plus_1
      light_entity_right: light.staande_lamp
      light_entity_both: light.woonkamer
      mode_selector: input_select.house_mode
- id: '1608714589824'
  alias: aqara slaapkamer
  description: ''
  use_blueprint:
    path: myown/aqara_doubleswitch_action_light.yaml
    input:
      switch_entity: sensor.slaapkamer_action
      light_entity_left: light.sk_spot
      light_entity_right: light.sk_ceiling
      light_entity_both: light.slaapkamer
      mode_selector: input_select.house_mode
- id: '1608714672968'
  alias: aqara keuken
  description: ''
  use_blueprint:
    path: myown/aqara_doubleswitch_action_light.yaml
    input:
      switch_entity: sensor.keuken_action
      light_entity_left: light.eetkamer
      light_entity_right: light.keuken
      light_entity_both: light.eetkamer, light.keuken
      mode_selector: input_select.house_mode
- id: '1651741431457'
  alias: notify if TV is missing
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.tv_samsung
    to: unavailable
    for:
      hours: 12
      minutes: 0
      seconds: 0
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: input_select.house_mode
      state: weg
  action:
  - service: persistent_notification.create
    data:
      message: 'TV unavailable '
      title: 'TV unavailable '
  mode: single

