default_config:
homeassistant:
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - /tmp

#logger
logger:
  default: warning
  logs:
#    custom_components.edgeos: debug
#    homeassistant.components: warn
#    homeassistant.components.device_tracker: debug
#    homeassistant.components.sensor.buienradar: debug
#    homeassistant.components.sensor.ring: debug
#    homeassistant.components.sensor.postnl: debug
#    homeassistant.components.binary_sensor.ring: debug
#    homeassistant.components.media_player.spotify: info
#    homeassistant.components.google_travel_time: debug
#    homeassistant.components.rest: debug
#    custom_components.mercedesmeapi: debug
#    custom_components.mercedesmeapi.sensor: info
#    custom_components.mercedesmeapi.apicontroller: debug
#    custom_components.mercedesmeapi.OAuth: debug
#    homeassistant.components.tplink: debug
#    custom_components.p2000: debug
    custom_components.multiscrape: debug    
    
http:
  #  ssl_certificate: /ssl/fullchain.pem
  #  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.20.20
    - 127.0.0.1
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

  # Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

python_script:


# View all events in a logbook
logbook:
  exclude:
    entities:
      - automation.update_alt_az_sensor
    entity_globs:
      - sensor.diskstation_*
      - sensor.edgeos_*
      - sensor.sun_*

recorder:
  #  db_url: !secret db_url
  exclude:
    domains:
      - updater
      - camera
    entities:
      - sun.sun
      - sensor.time
      - sensor.iss

influxdb:
  host: 192.168.3.6
  port: 8086
  username: !secret influxdb_user
  password: !secret influxdb_password
  exclude:
    domains:
      - updater
      - camera
      - automation
    entities:
      - sun.sun
      - sensor.time
      - sensor.iss
  tags_attributes:
    - friendly_name
    - device_class
  component_config_glob:
    "sensor.*humidity":
      override_measurement: humidity
    "sensor.*temperature":
      override_measurement: temperature
    "sensor.*battery":
      override_measurement: battery

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say


notify:
  - platform: html5
    name: webbrowser
    vapid_pub_key: !secret google_vapid_pub_key
    vapid_prv_key: !secret google_vapid_prv_key
    vapid_email: !secret google_vapid_email
#  - platform: pushover
#    name: pushover
#    api_key: !secret pushover_api
#    user_key: !secret pushover_user

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use


# Example configuration.yaml entry
gdacs:
  radius: 172
  latitude: 52.23677047848721
  longitude: 5.383300781250001

wake_on_lan:

zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#script include: !include_dir_merge_named include/scripts
#automation include: !include_dir_merge_named include/automations
