homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.6949
  longitude: 5.2030
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /tmp

# Show links to resources in log and frontend
#introduction:

#logger
logger:
  default: error
  logs: 
    homeassistant.components: warn
#    homeassistant.components.device_tracker: debug 
#    homeassistant.components.sensor.buienradar: debug
#    homeassistant.components.sensor.ring: debug
#    homeassistant.components.sensor.postnl: debug
#    homeassistant.components.binary_sensor.ring: debug
#   homeassistant.components.media_player.spotify: info
#    homeassistant.components.google_travel_time: debug
#    custom_components.mercedesmeapi: debug
#    custom_components.mercedesmeapi.sensor: info
#    custom_components.mercedesmeapi.apicontroller: debug
#    custom_components.mercedesmeapi.OAuth: debug
#

#hacs:
#  token: !secret my_github_access_token

# Enables the frontend
frontend:

# https://github.com/thomasloven/hass-browser_mod
#browser_mod:
#  devices:
#    95612154-b42299e6:
#      name: Desktop
#    ee15c3f5 b0c15c44:
#      name: Oneplus3
## Enables configuration UI
config:


# enable the person component
person:

lovelace:
  mode: yaml

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
#  ssl_certificate: /home/homeassistant/dehydrated/certs/foto-album.duckdns.org/fullchain.pem
#  ssl_key: /home/homeassistant/dehydrated/certs/foto-album.duckdns.org/privkey.pem
#  base_url: foto-album.duckdns.org:8123
  base_url: https://foto-album.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

  # Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

zeroconf:
ssdp:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - automations
      - calendar
      - input_boolean
      - input_datetime
      - input_number

# View all events in a logbook
logbook:
  exclude:
    entities:
      - automation.set_input_select_cast_devices_based_on_sensor_chromecast_devices
      - input_select.cast_devices

# Enables a map showing the location of tracked devices
map:



recorder:
#  db_url: !secret db_url
  exclude:
    domains:
      - weblink
      - updater
      - camera
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date
      - sensor.time
      - proximity.home2
      - sensor.iss

system_health:


influxdb:
  host: 192.168.1.6
  port: 8086
  username: !secret influxdb_user
  password: !secret influxdb_password
  exclude:
    domains:
      - weblink
      - updater
      - camera
      - automation
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date
      - sensor.time
      - proximity.home2
      - sensor.iss
  tags_attributes:
    - friendly_name
    - device_class
  component_config_glob:
    "sensor.*humidity":
      override_measurement: humidity
    "sensor.*temperature":
      override_measurement: temperature
    "sensor.*battery":
      override_measurement: battery
  
# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
#cloud:


notify:
  - platform: html5
    name: webbrowser
#    gcm_api_key: !secret google_firebase_key
#    gcm_sender_id: 836630737755
    vapid_pub_key: !secret google_vapid_pub_key
    vapid_prv_key: !secret google_vapid_prv_key
    vapid_email: !secret google_vapid_email
  - platform: pushover
    name: pushover
    api_key: !secret pushover_api
    user_key: !secret pushover_user


#sensor: !include sensors.yaml
zone: !include zones.yaml
#group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml