blueprint:
  name: Motion-activated Light Lightlevel
  description: Turn on a light when motion is detected.
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            domain: binary_sensor
            device_class: motion
    illu_entity:
      name: Illuminance of motion sensor
      selector:
        entity:
          filter:
            domain: sensor
            device_class: illuminance
    light_entity:
      name: Light
      selector:
        entity:
          filter:
            domain: light
    threshold_input:
      name: Light level input helper
      selector:
        entity:
          filter:
            domain: input_number

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

variables:
  motion_entity: !input motion_entity
  illu_entity: !input illu_entity
  light_level: "{{(states(illu_entity) |float)}}"
  threshhold_entity: !input threshold_input
  light_threshold: "{{states( threshhold_entity) | float}}"


condition:
  - "{{ light_level < light_threshold  }}"
  - condition: state
    entity_id: input_boolean.cleaningmode
    state: "off"

trigger:
  trigger: state
  entity_id: !input motion_entity
  to: "on"

action:
  - action: light.turn_on
    target:
      entity_id: !input light_entity
    data:
      transition: 2

  - wait_for_trigger:
      trigger: state
      entity_id: !input motion_entity
      to: "off"
  - not:
    - condition: state
      entity_id: !input light_entity
      state: "off"
  - action: light.turn_off
    target:
      entity_id: !input light_entity
    data:
      transition: 2
  - delay: 10
