batterywarning:
  name: batterywarning
  description: Create persistant warning when any battery is below 10%
iss:
  name: iss
  description: calculate ISS altitude angle above horizon from home location
set_list_from_sensor:
  name: set_list_from_sensor
  description: set an input helper with contents from a sensors device attribute
  fields:
    sensor:
      description: entity_id of sensor
    input_select:
      description: entity_id of input_select
smooth_fader:
  name: smooth_fader
  description: non linear fading.
  fields:
    entity_id:
      description: light.entity ; required
    duration:
      description: '00:00:00' ; required, time under 10 seconds is not advised
    brightness_start:
      description: 0-255 ; default: current
    brightness_end:
      description: 0-255 ; default: current
    brightness_curve:
      description: 'linear' or 'exp2' or 'exp5' or 'smooth' ; default: exp5
    temperature_start:
      description: 154-370 ; default: current 
    temperature_end:
      description: 154-370 ; default: current
    temperature_curve:
      description: 'linear' or 'exp2' or 'exp5' or 'smooth' ; default: exp2