- alias: 'button click slaapkamer  right '
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b42afb_click
      to: 'right'
  action:
    service_template: >
      {% if is_state('light.slaapkamer', 'off') %}
        script.turn_on_light
      {% else %}
        script.turn_off_light
      {% endif %}
    data:
      light_entities: light.slaapkamer
      kelvin: 2000
      brightness_pct: 33

- alias: 'button click slaapkamer  left '
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b42afb_click
      to: 'left'
  action:
    service_template: >
      {% if is_state('light.sk_spot_1', 'off') %}
        script.turn_on_light
      {% else %}
        script.turn_off_light
      {% endif %}
    data:
      light_entities: light.sk_spot_1, light.sk_spot_2
      kelvin: 5000
      brightness_pct: 100

- alias: 'button click slaapkamer  both '
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b42afb_click
      to: 'both'
  action:
    service_template: >
      {% if is_state('light.slaapkamer', 'off') %}
        script.turn_on_light
      {% else %}
        script.turn_off_light
      {% endif %}
    data:
        light_entities: light.sk_spot_1, light.sk_spot_2, light.slaapkamer

- alias: 'button long_click slaapkamer  right on '
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b42afb_click
      to: 'right_long'
  action:
    - service: script.dim_light
      data:
        light_entity: light.slaapkamer

- alias: 'button long_click slaapkamer  right off'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b42afb_click
      to: ''
      from: 'right_long'
  action:
    - service: homeassistant.turn_off
      entity_id: script.dim_light
    - service: homeassistant.turn_off
      entity_id: script.dim_light_loop
      
- alias: 'button long_click slaapkamer  left on '
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b42afb_click
      to: 'left_long'
  action:
    - service: script.dim_light
      data:
        light_entity: light.sk_spot_1, light.sk_spot_2

- alias: 'button long_click slaapkamer  left off'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b42afb_click
      to: ''
      from: 'left_long'
  action:
    - service: homeassistant.turn_off
      entity_id: script.dim_light
    - service: homeassistant.turn_off
      entity_id: script.dim_light_loop

- alias: 'button click slaapkamer  right_double '
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b42afb_click
      to: 'right_double'
  action:
    - service: switch.turn_off
      entity_id: switch.circadian_lighting_circadian_lighting
    - service: script.turn_on_light
      data_template:
        light_entities: light.slaapkamer
        kelvin: >
            {% set current = state_attr('light.slaapkamer', 'color_temp') |int %}
            {% if current <= 200 %}
              3000
            {% elif current <= 350  %}
              2000
            {% else %}
              6000
            {% endif %}
      
- alias: 'button click slaapkamer  left_double '
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b42afb_click
      to: 'left_double'
  action:
    - service: switch.turn_off
      entity_id: switch.circadian_lighting_circadian_lighting
    - service: script.turn_on_light
      data_template:
        light_entities: light.sk_spot_1, light.sk_spot_2
        kelvin: >
            {% set current = state_attr('light.sk_spot_1', 'color_temp') |int %}
            {% if current <= 200  %} 
              3000
            {% elif current <= 350  %}
              2000
            {% else %}
              6000
            {% endif %}