- alias: 'button click studeerkamer  right '
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a1cf_click
      to: 'right'
  action:
    service_template: >
      {% if is_state('group.lampen', 'off') %}
        script.turn_on_light
      {% else %}
        script.turn_off_light
      {% endif %}
    data:
      light_entities: group.lampen
      kelvin: 5000
      brightness_pct: 100

- alias: 'button click studeerkamer  left '
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a1cf_click
      to: 'left'
  action:
    service_template: >
      {% if is_state('light.computer', 'off') %}
        script.turn_on_light
      {% else %}
        script.turn_off_light
      {% endif %}
    data:
      light_entities: light.computer
      kelvin: 3000
      brightness_pct: 50

- alias: 'button click studeerkamer  both '
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a1cf_click
      to: 'both'
  action:
    service_template: >
      {% if is_state('group.lampen', 'off') %}
        script.turn_on_light
      {% else %}
        script.turn_off_light
      {% endif %}
    data:
        light_entities: light.computer, group.lampen

- alias: 'button long_click studeerkamer  right on '
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a1cf_click
      to: 'right_long'
  action:
    - service: script.dim_light
      data:
        light_entity: group.lampen

- alias: 'button long_click studeerkamer  right off'
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a1cf_click
      to: ''
      from: 'right_long'
  action:
    - service: homeassistant.turn_off
      entity_id: script.dim_light
    - service: homeassistant.turn_off
      entity_id: script.dim_light_loop
      
- alias: 'button long_click studeerkamer  left on '
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a1cf_click
      to: 'left_long'
  action:
    - service: script.dim_light
      data:
        light_entity: light.computer

- alias: 'button long_click studeerkamer  left off'
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a1cf_click
      to: ''
      from: 'left_long'
  action:
    - service: homeassistant.turn_off
      entity_id: script.dim_light
    - service: homeassistant.turn_off
      entity_id: script.dim_light_loop

- alias: 'button click studeerkamer  right_double '
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a1cf_click
      to: 'right_double'
  action:
    - service: switch.turn_off
      entity_id: switch.circadian_lighting_circadian_lighting
    - service: script.turn_on_light
      data_template:
        light_entities: group.lampen
        kelvin: >
            {% set current = state_attr('group.lampen', 'color_temp') |int %}
            {% if current <= 200 %}
              3000
            {% elif current <= 350  %}
              2000
            {% else %}
              6000
            {% endif %}
      
- alias: 'button click studeerkamer  left_double '
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a1cf_click
      to: 'left_double'
  action:
    - service: switch.turn_off
      entity_id: switch.circadian_lighting_circadian_lighting
    - service: script.turn_on_light
      data_template:
        light_entities: light.computer
        kelvin: >
            {% set current = state_attr('light.computer', 'color_temp') |int %}
            {% if current <= 200  %} 
              3000
            {% elif current <= 350  %}
              2000
            {% else %}
              6000
            {% endif %}