- alias: 'button click woonkamer  right '
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a149_click
      to: 'right'
  action:
    service_template: >
      {% if is_state('light.staande_lamp', 'off') %}
        script.turn_on_light
      {% else %}
        script.turn_off_light
      {% endif %}
    data:
      light_entities: light.staande_lamp
      kelvin: 2000
      brightness_pct: 50

- alias: 'button click woonkamer  left '
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a149_click
      to: 'left'
  action:
    service_template: >
      {% if is_state('light.hue_lightstrip_plus_1', 'off') %}
        script.turn_on_light
      {% else %}
        script.turn_off_light
      {% endif %}
    data:
      light_entities: light.hue_lightstrip_plus_1
      kelvin: 2000
      brightness_pct: 33

- alias: 'button click woonkamer  both '
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a149_click
      to: 'both'
  action:
    service_template: >
      {% if is_state('light.staande_lamp', 'off') %}
        script.turn_on_light
      {% else %}
        script.turn_off_light
      {% endif %}
    data:
        light_entities: light.hue_lightstrip_plus_1, light.staande_lamp

- alias: 'button long_click woonkamer  right on '
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a149_click
      to: 'right_long'
  action:
    - service: script.dim_light
      data:
        light_entity: light.staande_lamp

- alias: 'button long_click woonkamer  right off'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a149_click
      to: ''
      from: 'right_long'
  action:
    - service: homeassistant.turn_off
      entity_id: script.dim_light
    - service: homeassistant.turn_off
      entity_id: script.dim_light_loop
      
- alias: 'button long_click woonkamer  left on '
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a149_click
      to: 'left_long'
  action:
    - service: script.dim_light
      data:
        light_entity: light.hue_lightstrip_plus_1

- alias: 'button long_click woonkamer  left off'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a149_click
      to: ''
      from: 'left_long'
  action:
    - service: homeassistant.turn_off
      entity_id: script.dim_light
    - service: homeassistant.turn_off
      entity_id: script.dim_light_loop

- alias: 'button click woonkamer  right_double '
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a149_click
      to: 'right_double'
  action:
    - service: switch.turn_off
      entity_id: switch.circadian_lighting_circadian_lighting
    - service: script.turn_on_light
      data_template:
        light_entities: light.staande_lamp
        kelvin: >
            {% set current = state_attr('light.staande_lamp', 'color_temp') |int %}
            {% if current <= 200 %}
              3000
            {% elif current <= 350  %}
              2000
            {% else %}
              6000
            {% endif %}
      
- alias: 'button click woonkamer  left_double '
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002b4a149_click
      to: 'left_double'
  action:
    - service: switch.turn_off
      entity_id: switch.circadian_lighting_circadian_lighting
    - service: script.turn_on_light
      data_template:
        light_entities: light.hue_lightstrip_plus_1
        kelvin: >
            {% set current = state_attr('light.hue_lightstrip_plus_1', 'color_temp') |int %}
            {% if current <= 200  %} 
              3000
            {% elif current <= 350  %}
              2000
            {% else %}
              6000
            {% endif %}