devices:
  - devices.yaml
groups:
  - groups.yaml
mqtt:
  base_topic: zigbee2mqtt
  server: mqtts://core-mosquitto:8883
  user: mqtt
  password: '!nw7MiM07r6IVeJw'
  reject_unauthorized: false
serial:
  adapter: zstack
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_CC_49_61-if00-port0
advanced:
  log_level: debug
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  enabled: true
  port: 8099
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
version: 2
