group:
  windows:
    entities:
      - binary_sensor.slaapkamer_links_contact
      - binary_sensor.zolder_achter_rechts_contact
      - binary_sensor.slaapkamer_rechts_contact
      - binary_sensor.studeerkamer_raam_contact
      - binary_sensor.woonkamer_tuindeur_contact
      - binary_sensor.zolder_achter_links_contact
      - binary_sensor.bijkeuken_raam_contact
      - binary_sensor.zolder_overloop_contact
      - binary_sensor.badkamer_raam_contact
      - binary_sensor.woonkamer_raam_contact
  windows_kachel:
    entities:
      - binary_sensor.slaapkamer_rechts_contact
      - binary_sensor.studeerkamer_raam_contact
      - binary_sensor.woonkamer_tuindeur_contact
      - binary_sensor.badkamer_raam_contact
      - binary_sensor.woonkamer_raam_contact
      - binary_sensor.slaapkamer_links_contact
  doors:
    entities:
      - binary_sensor.voordeur_contact
      - binary_sensor.woonkamer_tuindeur_contact
      - binary_sensor.bijkeuken_deur_contact
alarm_control_panel:
  - platform: manual
    code_template: !secret alarm_code_template
input_text:
  last_alarm_trigger_reason:
    name: Last Alarm trigger sensor
    max: 255
automation:
  - alias: "leave home immidiate"
    id: "438709184787098346"
    trigger:
      - platform: state
        entity_id: input_select.arnoud_status
        to: "Net Weg"
    condition:
    - alias: "no guests in the house"
      condition: state
      entity_id: input_boolean.guests_boolean
      state: "off"
    action:
      - service: alarm_control_panel.alarm_arm_away
        target:
          entity_id: alarm_control_panel.ha_alarm
      - service: script.slow_flash_color_on_lights
        data:
          brightness_pct: 10
          xy_color:
            - 0.6091 
            - 0.3702
  - alias: "return home immidiate "
    id: "43246809632049861384906"
    trigger:
      - platform: state
        entity_id: input_select.arnoud_status
        to: "Net Thuis"
    action:
      - service: alarm_control_panel.alarm_disarm
        target:
          entity_id: alarm_control_panel.ha_alarm
        data:
          code: !secret alarm_code
  - alias: "return home delayed"
    id: "892340910348790"
    trigger:
      - platform: state
        entity_id: input_select.arnoud_status
        to: "Thuis"
    action:
      - service: alarm_control_panel.alarm_disarm
        target:
          entity_id: alarm_control_panel.ha_alarm
        data:
          code: !secret alarm_code
  - alias: "deur open en niet thuis"
    id: "3567312503718013980"
    trigger:
      platform: state
      entity_id: 
        - binary_sensor.bijkeuken_deur_contact
        - binary_sensor.voordeur_contact
      from: "off"
      to: "on"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.arnoud_status
            state: "Net Weg"
          - condition: state
            entity_id: input_select.arnoud_status
            state: "Weg"
    action:
      - service: notify.pushover
        data:
          message: "De {{states[trigger.to_state.domain][trigger.to_state.object_id].name}} is open"
          title: "Deur alarm"
          data:
            priority: 1
  
  - alias: "trigger alarm based on door & motion sensors if armed away"
    id: "521368393280359863"
    trigger:
      platform: state
      entity_id: 
        - binary_sensor.bijkeuken_deur_contact
        - binary_sensor.voordeur_contact
        - binary_sensor.hal_occupancy
        - binary_sensor.badkamer_raam_contact
        - binary_sensor.studeerkamer_raam_contact
        - binary_sensor.slaapkamer_links_contact
        - binary_sensor.slaapkamer_rechts_contact
        - binary_sensor.zolder_overloop_contact
        - binary_sensor.zolder_achter_links_contact
        - binary_sensor.zolder_achter_rechts_contact
        - binary_sensor.woonkamer_raam_contact
        - binary_sensor.woonkamer_tuindeur_contact
        - binary_sensor.bijkeuken_raam_contact
      from: "off"
      to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_away
    action:
      - service: alarm_control_panel.alarm_trigger
        target:
          entity_id: alarm_control_panel.ha_alarm
      - service: input_text.set_value
        target:
          entity_id: input_text.last_alarm_trigger_reason
        data:
          value: " {{states.binary_sensor|rejectattr('state' , 'eq' , 'off')|selectattr('attributes.device_class', 'in' , ['window', 'motion', 'door'])|map(attribute='name')|list}}"
  #            {%- set ns = namespace(first=false) %}
  #            {%- for sensor in dict(states.binary_sensor|groupby('state'))['on'] %}
  #              {%- set d_class = sensor.attributes.device_class %}
  #              {%- if d_class != 'window' and d_class != 'motion' and d_class != 'door'%}
  #                {%- if loop.first %}{%set ns.first =true %}{% endif %}
  #              {%- else %}
  #                {%- if loop.first or ns.first  %}{% set ns.first =false%}{% else %}, {% endif %}
  #                {{ sensor.name | lower }}
  #              {%- endif %}
  #              {%- if loop.last %}{% endif %}
  #            {%-  endfor  %}
  - alias: "Send notification when alarm triggered"
    id: "462313490860234890"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: "triggered"
    action:
      - service: notify.pushover
        data:
          title: "ALARM"
          message: "ALARM! The alarm has been triggered by {{states('input_text.last_alarm_trigger_reason')}}"
          data:
            priority: 1
#      - service: browser_mod.command
#        data:
#          command: more-info
#          entity_id: alarm_control_panel.ha_alarm

  - alias: "Sound alarm if  trigger remains for 2 minutes"
    id: "7680218940823460"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: "triggered"
        for: "00:01:55"
    action:
      - service: tts.google_say
        target:
          entity_id: media_player.speakers
        data:
          message: "Alarm! Alarm! Alarm! indringer in huis!"
          language: "nl"
      - service: scene.create
        data:
          scene_id: before_alarm
          snapshot_entities:
            - light.computer
            - light.hue_color_pendant_up_1
            - light.hue_color_pendant_down_1
            - light.hal
            - light.sk_ceiling
            - light.staande_lamp
            - light.keuken
            - light.trap_hal
            - light.overloop
            - light.sk_duo_spot_1
            - light.sk_duo_spot_2
      - service: light.turn_on
        target:
          entity_id: 
            - light.computer
            - light.hue_color_pendant_up_1
            - light.hue_color_pendant_down_1
            - light.hal
            - light.sk_ceiling
            - light.staande_lamp
            - light.keuken
        data:
          color_name: white
          brightness_pct: 100
      - service: light.turn_on
        target:
          entity_id: 
            - light.trap_hal
            - light.overloop
            - light.sk_duo_spot_1
            - light.sk_duo_spot_2
        data:
          color_temp: 153
          brightness_pct: 100
      - service: script.flash_lights


  - alias:  "turn lights on with smoke alarm"
    id: "e3f30eef-29a9-43d3-8fae-c63ce23b8ecb"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.0x000d6f001624f569_smoke
          - binary_sensor.0x000d6f001624f85e_smoke
          - binary_sensor.0x000d6f00162c1bfd_smoke
        to: "on"
    condition: []
    action:
      - service: notify.pushover
        data:
          message: "De {{states[trigger.to_state.domain][trigger.to_state.object_id].name}} detecteerd rook. test: {{state_attr(trigger.entity_id, 'test' )}}"
          title: "Rook alarm"
          data:
            priority: 1
      - service: scene.create
        data:
          scene_id: before_smokealarm
          snapshot_entities:
            - light.hue_lightstrip_plus_1
            - light.staande_lamp
            - light.hue_color_pendant_down_1
            - light.hue_color_pendant_up_1
            - light.computer
            - light.hal
            - light.zoldervoor
            - light.zolderachter
            - light.sk_ceiling
            - light.sk_duo_spot_1
            - light.sk_duo_spot_2
            - light.overloop
            - light.keuken_1
            - light.keuken_2
            - light.keuken_3
            - light.trap_hal
      - service: light.turn_on
        target:
          entity_id: 
            - light.computer
            - light.hue_color_pendant_down_1
            - light.hue_color_pendant_up_1
            - light.hal
            - light.sk_ceiling
            - light.staande_lamp
            - light.keuken_1
            - light.keuken_2
            - light.keuken_3
        data:
          color_name: white
          brightness_pct: 100
      - service: light.turn_on
        target:
          entity_id: 
            - light.trap_hal
            - light.overloop
            - light.sk_duo_spot_1
            - light.sk_duo_spot_2
        data:
          color_temp: 153
          brightness_pct: 100
  - alias: "Turn lights back to before when smoke alarm clears"
    id: "7ba56b40-b860-4c89-ab45-6f5306bfa7c1"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.0x000d6f001624f569_smoke
          - binary_sensor.0x000d6f001624f85e_smoke
          - binary_sensor.0x000d6f00162c1bfd_smoke
        from: "on"
        to: "off"
        for: 
          minutes: 5
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.before_smokealarm
        data:
          transition: 2
  - alias: "clear lights if alarm trigger is removed"
    id: "6673b7e4-ef25-4aaf-ba3a-1be9d660649c"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        from: "triggered"
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.before_alarm
        data:
          transition: 2