group:
  windows:
    entities:
      - binary_sensor.slaapkamer_links_contact
      - binary_sensor.zolder_achter_rechts_contact
      - binary_sensor.slaapkamer_rechts_contact
      - binary_sensor.studeerkamer_raam_contact
      - binary_sensor.woonkamer_tuindeur_contact
      - binary_sensor.zolder_achter_links_contact
      - binary_sensor.bijkeuken_raam_contact
      - binary_sensor.zolder_overloop_contact
      - binary_sensor.badkamer_raam_contact
      - binary_sensor.woonkamer_raam_contact
  windows_kachel:
    entities:
      - binary_sensor.slaapkamer_rechts_contact
      - binary_sensor.studeerkamer_raam_contact
      - binary_sensor.woonkamer_tuindeur_contact
      - binary_sensor.badkamer_raam_contact
      - binary_sensor.woonkamer_raam_contact
      - binary_sensor.slaapkamer_links_contact
  doors:
    entities:
      - binary_sensor.voordeur_contact
      - binary_sensor.woonkamer_tuindeur_contact
      - binary_sensor.bijkeuken_deur_contact
alarm_control_panel:
  - platform: manual
    code_template: !secret alarm_code_template
input_text:
  last_alarm_trigger_reason:
    name: Last Alarm trigger sensor
    max: 255
automation:
  - alias: "leave home immidiate"
    id: "438709184787098346"
    trigger:
      - platform: state
        entity_id: input_select.arnoud_status
        to: "Net Weg"
    condition:
    - alias: "no guests in the house"
      condition: state
      entity_id: input_boolean.guests_boolean
      state: "Off"
    action:
      - service: alarm_control_panel.alarm_arm_away
        target:
          entity_id: alarm_control_panel.ha_alarm
  - alias: "return home immidiate "
    id: "43246809632049861384906"
    trigger:
      - platform: state
        entity_id: input_select.arnoud_status
        to: "Net Thuis"
    action:
      - service: alarm_control_panel.alarm_disarm
        target:
          entity_id: alarm_control_panel.ha_alarm
        data:
          code: !secret alarm_code
  - alias: "return home delayed"
    id: "892340910348790"
    trigger:
      - platform: state
        entity_id: input_select.arnoud_status
        to: "Thuis"
    action:
      - service: alarm_control_panel.alarm_disarm
        target:
          entity_id: alarm_control_panel.ha_alarm
        data:
          code: !secret alarm_code
  - alias: "deur open en niet thuis"
    id: "3567312503718013980"
    trigger:
      platform: state
      entity_id: 
        - binary_sensor.bijkeuken_deur_contact
        - binary_sensor.voordeur_contact
      from: "off"
      to: "on"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.arnoud_status
            state: "Net Weg"
          - condition: state
            entity_id: input_select.arnoud_status
            state: "Weg"
    action:
      - service: notify.pushover
        data:
          message: "De {{states[trigger.to_state.domain][trigger.to_state.object_id].name}} is open"
          title: "Deur alarm"
          data:
            priority: 1
  
  - alias: "trigger alarm based on door & motion sensors if armed away"
    id: "521368393280359863"
    trigger:
      platform: state
      entity_id: 
        - binary_sensor.bijkeuken_deur_contact
        - binary_sensor.voordeur_contact
        - binary_sensor.overloop_occupancy
        - binary_sensor.traphal_occupancy
        - binary_sensor.hal_occupancy
        - binary_sensor.badkamer_raam_contact
        - binary_sensor.studeerkamer_raam_contact
        - binary_sensor.slaapkamer_links_contact
        - binary_sensor.slaapkamer_rechts_contact
        - binary_sensor.zolder_overloop_contact
        - binary_sensor.zolder_achter_links_contact
        - binary_sensor.zolder_achter_rechts_contact
        - binary_sensor.woonkamer_raam_contact
        - binary_sensor.woonkamer_tuindeur_contact
        - binary_sensor.bijkeuken_raam_contact
      from: "off"
      to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_away
    action:
      - service: alarm_control_panel.alarm_trigger
        target:
          entity_id: alarm_control_panel.ha_alarm
      - service: input_text.set_value
        target:
          entity_id: input_text.last_alarm_trigger_reason
        data:
          value: " {{states.binary_sensor|rejectattr('state' , 'eq' , 'off')|selectattr('attributes.device_class', 'in' , ['window', 'motion', 'door'])|map(attribute='name')|list}}"
  #            {%- set ns = namespace(first=false) %}
  #            {%- for sensor in dict(states.binary_sensor|groupby('state'))['on'] %}
  #              {%- set d_class = sensor.attributes.device_class %}
  #              {%- if d_class != 'window' and d_class != 'motion' and d_class != 'door'%}
  #                {%- if loop.first %}{%set ns.first =true %}{% endif %}
  #              {%- else %}
  #                {%- if loop.first or ns.first  %}{% set ns.first =false%}{% else %}, {% endif %}
  #                {{ sensor.name | lower }}
  #              {%- endif %}
  #              {%- if loop.last %}{% endif %}
  #            {%-  endfor  %}
  - alias: "Send notification when alarm triggered"
    id: "462313490860234890"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: "triggered"
    action:
      - service: notify.pushover
        data:
          title: "ALARM"
          message: "ALARM! The alarm has been triggered by {{states('input_text.last_alarm_trigger_reason')}}"
          data:
            priority: 1
      - service: browser_mod.command
        data:
          command: more-info
          entity_id: alarm_control_panel.ha_alarm

  - alias: "Sound alarm if  trigger remains for 2 minutes"
    id: "7680218940823460"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: "triggered"
        for: "00:01:55"
    action:
      - service: script.both_speakers
        data:
          tekst: "Alarm! Alarm! Alarm! indringer in huis! "
      - service: light.turn_on
        target:
          entity_id: 
            - light.computer
            - light.eettafel
            - light.hal
            - light.sk_ceiling
            - light.staande_lamp
            - light.keuken
        data:
          color_name: white
          brightness_pct: 100
      - service: light.turn_on
        target:
          entity_id: 

            - light.trap_hal
            - light.overloop
            - light.sk_duo_spot_1
            - light.sk_duo_spot_2
        data:
          color_temp: 153
          brightness_pct: 100
      - service: script.flash_lights
