automation:
  - alias: "send route to car"
    id: "03341c42-1881-4af4-aa3a-d2f7d564c073"
    trigger:
      - platform: state
        entity_id: sensor.afspraak_latlong
    condition:
      - "{{trigger.from_state.attributes.position != trigger.to_state.attributes.position}}"
      - "{{distance(state_attr('sensor.afspraak_latlong','position')['lat'], state_attr('sensor.afspraak_latlong','position')['lng'], 'device_tracker.kb2003')>=0.2}}"
    action:
      - service: mbapi2020.send_route
        data:
          vin: "W1K3F8HB2PV155037"
          title: "{{states('sensor.afspraak_latlong')}}"
          latitude: "{{state_attr('sensor.afspraak_latlong','position')['lat']}}"
          longitude: "{{state_attr('sensor.afspraak_latlong','position')['lng']}}"
          city: "{{state_attr('sensor.afspraak_latlong','address')['city']}}"
          street: "{{state_attr('sensor.afspraak_latlong','address')['street']}}"
          postcode: "{{state_attr('sensor.afspraak_latlong','address')['postalCode']}}"

template:
  - sensor:
    - name: "r_272_pb_park_brake_wear"
      unique_id: "ca51ddc4-fece-4c7a-9726-542c69b00b11"
      state: "{{ state_attr('binary_sensor.r_272_pb_park_brake_status', 'preWarningBrakeLiningWear') }}"
      attributes:
        vin: "W1K3F8HB2PV155037"
    - name: "r_272_pb_lock_status"
      unique_id: "08ea6481-1248-4b28-9db2-ee67ed34c9d1"
      state: >-
        {% if is_state('sensor.r_272_pb_lock', '0') %}
          Open
        {% elif is_state('sensor.r_272_pb_lock', '1') %}
          Intern vergrendeld
        {% elif is_state('sensor.r_272_pb_lock', '2') %}
          Extern vergrendeld
        {% elif is_state('sensor.r_272_pb_lock', '3') %}
          Selectief ontgrendeld
        {% else %}
          Onbekend
        {% endif %}
      icon: >
        {% if is_state('sensor.r_272_pb_lock', '0') %}
          mdi:lock-open-variant-outline
        {% else %}
          mdi:lock-outline
        {% endif %}
      attributes:
        vin: "W1K3F8HB2PV155037"
    - name: "r_272_pb_serviceintervaldays"
      unique_id: "2e113082-7dad-4c25-ad75-7905870a30c0"
      state: "{{ state_attr('sensor.r_272_pb_odometer', 'serviceintervaldays') | int }}"
      attributes:
        vin: "W1K3F8HB2PV155037"
      ## Door status
    - name: "r_272_pb_door_open_rearleft"
      unique_id: "1d8274b7-1e44-45b1-979a-5d9866f1e8af"
      state: "{{state_attr('sensor.r_272_pb_lock', 'doorstatusrearleft')}}"
      icon: "mdi:car-door"
      attributes:
        vin: "W1K3F8HB2PV155037"
    - name: "r_272_pb_door_open_rearright"
      unique_id: "fff23bbf-f829-46d1-b1f8-2958c3d09572"
      state: "{{state_attr('sensor.r_272_pb_lock', 'doorstatusrearright')}}"
      icon: "mdi:car-door"
      attributes:
        vin: "W1K3F8HB2PV155037"
    - name: "r_272_pb_door_open_frontright"
      unique_id: "1f08dc1b-dd88-4d2f-82ac-f7725eab46af"
      state: "{{state_attr('sensor.r_272_pb_lock', 'doorstatusfrontright')}}"
      icon: "mdi:car-door"
      attributes:
        vin: "W1K3F8HB2PV155037"
    - name: "r_272_pb_door_open_frontleft"
      unique_id: "c162c911-6162-42ed-bf2c-c491f6a87780"
      state: "{{state_attr('sensor.r_272_pb_lock', 'doorstatusfrontleft')}}"
      icon: "mdi:car-door"
      attributes:
        vin: "W1K3F8HB2PV155037"
    - name: "r_272_pb_door_open_deck"
      unique_id: "56b733d6-12c2-4627-ab1f-af48d6e86bbf"
      state: "{{state_attr('sensor.r_272_pb_lock', 'decklidstatus')}}"
      icon: "mdi:car-door"
      attributes:
        vin: "W1K3F8HB2PV155037"
    - name: "r_272_pb_door_open_hood"
      unique_id: "e3bd6a7f-816f-4e33-a6a7-d2d4e731ec63"
      state: "{{state_attr('sensor.r_272_pb_lock', 'engineHoodStatus')}}"
      icon: >
        {%if state_attr("sensor.r_272_pb_lock", "engineHoodStatus") %}
          "mdi:car-door"
        {% else %}
          "mdi:none"
        {% endif %}
      attributes:
        vin: "W1K3F8HB2PV155037"
      ### locks
    - name: "r_272_pb_lock_front_right"
      unique_id: "dd1286d3-5859-4401-a170-307b13f977f7"
      state: >-
        {% if is_state_attr('sensor.r_272_pb_lock', 'doorlockstatusfrontright', false)%}
            Closed
        {% else %}
            Open
        {% endif %}
      icon: >
        {% if is_state_attr('sensor.r_272_pb_lock', 'doorlockstatusfrontright', false)%}
          mdi:lock-outline
        {% else %} 
          mdi:lock-open-variant-outline
        {% endif %}
      attributes:
        vin: "W1K3F8HB2PV155037"
    - name: "r_272_pb_lock_front_left"
      unique_id: "6d8d5344-5d7f-4047-bcf7-caa6f979ae15"
      state: >-
        {% if is_state_attr('sensor.r_272_pb_lock', 'doorlockstatusfrontleft', false)%}
            Closed
        {% else %}
            Open
        {% endif %}
      icon: >
        {% if is_state_attr('sensor.r_272_pb_lock', 'doorlockstatusfrontleft', false)%}
          mdi:lock-outline
        {% else %} 
          mdi:lock-open-variant-outline
        {% endif %}
      attributes:
        vin: "W1K3F8HB2PV155037"
    - name: "r_272_pb_lock_rear_right"
      unique_id: "ffadaf22-7dc1-4f1c-a850-5d97c8d9f3dd"
      state: >-
        {% if is_state_attr('sensor.r_272_pb_lock', 'doorlockstatusrearright', false)%}
            Closed
        {% else %}
            Open
        {% endif %}
      icon: >
        {% if is_state_attr('sensor.r_272_pb_lock', 'doorlockstatusrearright', false)%}
          mdi:lock-outline
        {% else %} 
          mdi:lock-open-variant-outline
        {% endif %}
      attributes:
        vin: "W1K3F8HB2PV155037"
    - name: "r_272_pb_lock_rear_left"
      unique_id: "d95a9adf-011a-4699-b102-5c1794a11a6f"
      state: >-
        {% if is_state_attr('sensor.r_272_pb_lock', 'doorlockstatusrearleft', false)%}
            Closed
        {% else %}
            Open
        {% endif %}
      icon: >
        {% if is_state_attr('sensor.r_272_pb_lock', 'doorlockstatusrearleft', false)%}
          mdi:lock-outline
        {% else %} 
          mdi:lock-open-variant-outline
        {% endif %}
      attributes:
        vin: "W1K3F8HB2PV155037"
    - name: "r_272_pb_lock_trunk"
      unique_id: "0c1cb4cf-4e91-4570-bcd3-cd00f63c2193"
      state: >-
        {% if is_state_attr('sensor.r_272_pb_lock', 'doorlockstatusdecklid', false)%} 
            Closed
        {% else %}
            Open
        {% endif %}
      icon: >
        {% if is_state_attr('sensor.r_272_pb_lock', 'doorlockstatusdecklid', false)%} 
          mdi:lock-outline
        {% else %}
          mdi:lock-open-variant-outline
        {% endif %}
      attributes:
        vin: "W1K3F8HB2PV155037"
    - name: "r_272_pb_lock_gas"
      unique_id: "3fe5ebbc-9d27-4a8e-ab71-98df4aedb4e5"
      state: >-
        {% if is_state_attr('sensor.r_272_pb_lock', 'doorlockstatusgas', false)%} 
            Closed
        {% else %}
            Open
        {% endif %}
      icon: >
        {% if is_state_attr('sensor.r_272_pb_lock', 'doorlockstatusgas', false)%} 
          mdi:lock-outline
        {% else %}
          mdi:lock-open-variant-outline
        {% endif %}
      attributes:
        vin: "W1K3F8HB2PV155037"
      ## windows
    - name: "r_272_pb_window_front_left"
      unique_id: "9d7d4a1c-548f-4bbd-b96e-787829e61626"
      state: >-
        {% if is_state_attr('binary_sensor.r_272_pb_windows_closed', 'windowstatusfrontleft', '2')%} 
            Closed
        {% else %}
            Open
        {% endif %}
      icon: >
        {% if is_state_attr('binary_sensor.r_272_pb_windows_closed', 'windowstatusfrontleft', '2')%} 
          mdi:window-closed
        {% else %}
          mdi:window-open
        {% endif %}
      attributes:
        vin: "W1K3F8HB2PV155037"
    - name: "r_272_pb_window_front_right"
      unique_id: "620df868-4cba-4c6b-8820-d78a5472d567"
      state: >-
        {% if is_state_attr('binary_sensor.r_272_pb_windows_closed', 'windowstatusfrontright', '2')%} 
            Closed
        {% else %}
            Open
        {% endif %}
      icon: >
        {% if is_state_attr('binary_sensor.r_272_pb_windows_closed', 'windowstatusfrontright', '2')%} 
          mdi:window-closed
        {% else %}
          mdi:window-open
        {% endif %}
      attributes:
        vin: "W1K3F8HB2PV155037"
    - name: "r_272_pb_window_rear_left"
      unique_id: "d3b568a8-dd14-4780-bbcb-24ea01c27da1"
      state: >-
        {% if is_state_attr('binary_sensor.r_272_pb_windows_closed', 'windowstatusrearleft', '2')%} 
            Closed
        {% else %}
            Open
        {% endif %}
      icon: >
        {% if is_state_attr('binary_sensor.r_272_pb_windows_closed', 'windowstatusrearleft', '2')%} 
          mdi:window-closed
        {% else %}
          mdi:window-open
        {% endif %}
      attributes:
        vin: "W1K3F8HB2PV155037"
    - name: "r_272_pb_window_rear_right"
      unique_id: "3b65f218-240d-44ca-8608-6255b4193404"
      state: >-
        {% if is_state_attr('binary_sensor.r_272_pb_windows_closed', 'windowstatusrearright', '2')%} 
            Closed
        {% else %}
            Open
        {% endif %}
      icon: >
        {% if is_state_attr('binary_sensor.r_272_pb_windows_closed', 'windowstatusrearright', '2')%} 
          mdi:window-closed
        {% else %}
          mdi:window-open
        {% endif %}
      attributes:
        vin: "W1K3F8HB2PV155037"
