google:
  client_id: 836630737755-pr91j52c6n1700mvlsu5tn3tn4maoel6.apps.googleusercontent.com
  client_secret: !secret google_cal_apikey

input_boolean:
  f1_announcements:
    name: announce F1 races
input_datetime:
  pre_heat_time:
    name: Input with both date and time
    has_date: true
    has_time: true
  bedtime:
    name: bedtime
    has_date: true
    has_time: true
  wakeuptime:
    name: wakeuptime
    has_date: true
    has_time: true
  wakeuplight_time:
    name: alarmtime
    has_date: true
    has_time: true
camera:
  - platform: generic
    name: Destination
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?key={{states("sensor.google_api_key")}}&center={{state_attr("calendar.abuurmangmailcom", "location")}}&zoom=17&size=600x300&maptype=roadmap&markers=color:blue%7C{{state_attr("calendar.abuurmangmailcom", "location")}}
    limit_refetch_to_url_change: true

sensor:
  - platform: time_date
    display_options:
      - "time"
  - platform: template
    sensors:
      cal_title:
        value_template: '{{ state_attr("calendar.abuurmangmailcom", "message") | replace("#alarm", "") }}'
        friendly_name: "Title"
      cal_travelmode:
        value_template: >-
          {% if "#ov" in state_attr("calendar.abuurmangmailcom", "message") %}
            transit
          {% else %}
            driving
          {% endif %}
      cal_location:
        value_template: >
          {% if is_state_attr("calendar.abuurmangmailcom", "location", "") or is_state_attr("calendar.abuurmangmailcom", "location", "unknown") %}
            {{state_attr("zone.home", "latitude")}},{{state_attr("zone.home", "longitude")}}
          {% else %}
            {{ state_attr("calendar.abuurmangmailcom", "location") }}
          {% endif %}
      cal_location_alarm:
        value_template: >
          {% if is_state_attr("calendar.alarm", "location", "") or is_state_attr("calendar.alarm", "location", "unknown") %}
            {{state_attr("zone.home", "latitude")}},{{state_attr("zone.home", "longitude")}}
          {% else %}
            {{ state_attr("calendar.alarm", "location") }}
          {% endif %}
        friendly_name: "Location"
      cal_reminders_name:
        value_template: '{{ state_attr("calendar.reminders", "message") | replace("#reminders", "")}}'
        friendly_name: "Title"
      cal_reminders_date:
        value_template: >
          {% set tz = as_timestamp(now())|timestamp_custom('%z') %}
          {% set time = state_attr("calendar.reminders", "start_time") + tz %}
          {{as_timestamp(time)|timestamp_local}}
        friendly_name: "Start Time"
      cal_start_time:
        value_template: >
          {% set tz = as_timestamp(now())|timestamp_custom('%z') %}
          {% set time = state_attr("calendar.abuurmangmailcom", "start_time") + tz %}
          {{as_timestamp(time)|timestamp_local}}
        friendly_name: "Start Time"
      cal_start_time_unix:
        value_template: >
          {% set tz = as_timestamp(now())|timestamp_custom('%z') %}
          {% set time = state_attr("calendar.abuurmangmailcom", "start_time") + tz %}
          {{as_timestamp(time)}}
        friendly_name: "Start Time"
      calc_leave_time:
        value_template: >
          {% set tz = as_timestamp(now())|timestamp_custom('%z') %}
          {% set time = state_attr("calendar.abuurmangmailcom", "start_time") + tz %}
          {% set starttime = as_timestamp(time) %}    
          {% set duration = state_attr("sensor.google_travel_time_driving", "duration") %}
          {%if duration == None %}
            {{ starttime  | timestamp_custom("%Y-%m-%d %H:%M") }}
          {% else %}
            {%if duration.split(" ")[2]==Null %}
              {{ (starttime  - (duration.split(" ")[0]  | int * 60 )) | timestamp_custom("%Y-%m-%d %H:%M") }}
            {% else %}
              {{ (starttime - (duration.split(" ")[0] | int *3600 + duration.split(" ")[2] | int *60 )) | timestamp_custom("%Y-%m-%d %H:%M")}}
            {% endif %} 
          {% endif %}
        friendly_name: "Leave Time"
      calc_leave_time_unix:
        value_template: >
          {% set tz = as_timestamp(now())|timestamp_custom('%z') %}
          {% set time = state_attr("calendar.abuurmangmailcom", "start_time") + tz %}
          {% set starttime = as_timestamp(time) %}    
          {% set duration = state_attr("sensor.google_travel_time_driving", "duration") %}
          {%if duration == None %}
            {{ starttime }}
          {% else %}
            {%if duration.split(" ")[2]==Null %}
              {{ (starttime  - (duration.split(" ")[0]  | int * 60 )) }}
            {% else %}
              {{ (starttime - (duration.split(" ")[0] | int *3600 + duration.split(" ")[2] | int *60 )) }}
            {% endif %} 
          {% endif %}
      calc_leave_time_alarm:
        value_template: >
          {% set tz = as_timestamp(now())|timestamp_custom('%z') %}
          {% set time = state_attr("calendar.alarm", "start_time") + tz %}
          {% set starttime = as_timestamp(time) %}   
          {% set duration = state_attr("sensor.google_travel_time_alarm", "duration") %}
          {%if duration == None %}
            {{ starttime  | timestamp_custom("%Y-%m-%d %H:%M") }}
          {% else %}
            {%if duration.split(" ")[2]==Null %}
              {{ (starttime  - (duration.split(" ")[0]  | int * 60 )) | timestamp_custom("%Y-%m-%d %H:%M") }}
            {% else %}
              {{ (starttime - (duration.split(" ")[0] | int *3600 + duration.split(" ")[2] | int *60 )) | timestamp_custom("%Y-%m-%d %H:%M")}}
            {% endif %} 
          {% endif %}
        friendly_name: "Alarm Leave Time"
      cal_contacts_start_time:
        value_template: >
          {% set tz = as_timestamp(now())|timestamp_custom('%z') %}
          {% set time = state_attr("calendar.contacts", "start_time") + tz %}
          {{as_timestamp(time)|timestamp_custom("%m-%d-%Y")}}
        friendly_name: "Datum"
      cal_contacts_message:
        value_template: '{{state_attr("calendar.contacts", "message")}}'
        friendly_name: "Contacts:"
      cal_title_f1:
        value_template: '{{ state_attr("calendar.2020_fia_formula_one_world_championship_race_calendar", "message") }}'
        friendly_name: "Title"
      cal_start_time_f1:
        value_template: >
          {% set tz = as_timestamp(now())|timestamp_custom('%z') %}
          {% if state_attr('calendar.2020_fia_formula_one_world_championship_race_calendar', 'start_time') == None %}
            None
          {% else %}
            {{ as_timestamp(state_attr("calendar.2020_fia_formula_one_world_championship_race_calendar", "start_time") + tz )   | timestamp_local }}
          {% endif %}

automation:
  - alias: "vertrek melding"
    id: "567812438901831653879"
    trigger:
      platform: time_pattern
      seconds: 00
    condition:
      - condition: template
        value_template: >
          {% set tz = as_timestamp(now())|timestamp_custom('%z') %}
          {{ now().strftime("%D %H:%M") == ( (as_timestamp(states("sensor.calc_leave_time") + tz ) - 300 )| timestamp_custom("%D %H:%M", 1)) }}
      - condition: template
        value_template: '{{(states("sensor.calc_travel_time")|int)>120}}'

    action:
      - service: script.both_speakers
        data:
          tekst: >
            {% set reistijd = states("sensor.calc_travel_time") %}
            {%if reistijd=="unknown" %} 
              Het is tijd om naar {{states('sensor.cal_title')}} te gaan. De reistijd is onbekend.
            {% else %}
              Het is tijd om naar {{states('sensor.cal_title')}} te gaan. De reistijd bedraagt {{ reistijd | int /60 |round }} minuten
            {% endif %}
      - service: tts.google_say
        entity_id: media_player.desktop
        data:
          message: >
            {% set reistijd = states("sensor.calc_travel_time") %}
            {%if reistijd=="unknown" %} 
              Het is tijd om naar {{states('sensor.cal_title')}} te gaan. De reistijd is onbekend.
            {% else %}
              Het is tijd om naar {{states('sensor.cal_title')}} te gaan. De reistijd bedraagt {{ reistijd | int /60 |round }} minuten
            {% endif %}
          cache: false
          language: "nl"
  - alias: "F1 begin wedstrijd"
    id: "3478021346858103290"
    trigger:
      platform: time_pattern
      seconds: 00
    condition:
      - condition: template
        value_template: >
          {% set tz = as_timestamp(now())|timestamp_custom('%z') %}
          {% if state_attr('calendar.2020_fia_formula_one_world_championship_race_calendar', 'start_time') == None %}
            False
          {% else %}
            {{ now().strftime('%D %H:%M') == ( (as_timestamp(state_attr("calendar.2020_fia_formula_one_world_championship_race_calendar", "start_time") + tz )-600)   | timestamp_custom('%D %H:%M', 1)) }}
          {% endif %}
      - condition: state
        entity_id: input_boolean.f1_announcements
        state: "on"
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.arnoud_status
            state: "Thuis"
          - condition: state
            entity_id: input_select.arnoud_status
            state: "Net Thuis"
    #    action:
    #      - service: script.both_speakers
    #        data:
    #          tekst: 'De {{state_attr("calendar.2020_fia_formula_one_world_championship_race_calendar", "message")|striptags}} begint over tien minuten '
    action:
      - service: tts.google_say
        entity_id: media_player.speakers
        data:
          message: >
            De {{state_attr("calendar.2020_fia_formula_one_world_championship_race_calendar", "message")}} begint over tien minuten
          cache: false
          language: "nl"
      - service: homeassistant.turn_on
        entity_id: light.media_group
  - alias: "set time input helpers"
    id: "4d6474f6-4a53-4c54-ae47-66326ad68133"
    trigger:
      platform: state
      entity_id: sensor.calc_leave_time_alarm
    variables:
      alarm_time: >
        {% set tz = as_timestamp(now())|timestamp_custom('%z') %}
        {% if states("sensor.calc_leave_time_alarm") == "unknown" %}
          09:00
        {% else %}
          {{as_timestamp(states("sensor.calc_leave_time_alarm")+ tz ) - ((states("input_number.wul_time_before_leave") |int ) * 60) }}
        {% endif %}
    action:
      - service: input_datetime.set_datetime
        entity_id: input_datetime.wakeuplight_time
        data:
          timestamp: "{{alarm_time}}"
      - service: input_datetime.set_datetime
        entity_id: input_datetime.pre_heat_time
        data:
          timestamp: "{{alarm_time - 1800 }}"
      - service: input_datetime.set_datetime
        entity_id: input_datetime.bedtime
        data:
          timestamp: "{{alarm_time - (7*3600+900)}}"
      - service: input_datetime.set_datetime
        entity_id: input_datetime.wakeuptime
        data:
          timestamp: "{{alarm_time +900}}"

script:
  test_f1_announce:
    sequence:
      - service: tts.google_say
        entity_id: media_player.speakers
        data:
          message: >
            De {{state_attr("calendar.2020_fia_formula_one_world_championship_race_calendar", "message")}} begint over tien minuten
          cache: false
          language: "nl"
