input_boolean:
  cleaningmode:
    name: cleaning mode
automation:
  - alias: 'cleaning mode on'
    id: '0643587777777738989'
    trigger:
      - platform: state
        entity_id: input_boolean.cleaningmode
        to: 'on'
    action:
      - service: script.cleaningmode_on
  - alias: 'cleaning mode off'
    id: '6753290123480'
    trigger:
      - platform: state
        entity_id: input_boolean.cleaningmode
        to: 'off'
    action:
      - service: script.cleaningmode_off
  - alias: 'hue dimmer switch on'
    id: '167521365098632509816235'
    trigger: 
      - platform: state
        entity_id: remote.hue_dimmer_switch_1
        to: '1_click_up'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.cleaningmode
  - alias: 'hue dimmer switch off'
    id: '87504935709864210938'
    trigger: 
      - platform: state
        entity_id: remote.hue_dimmer_switch_1
        to: '4_click_up'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.cleaningmode
  - alias: 'jacqueline-binnen'
    id: 142c8938-9513-48fe-9345-01f55a7992a9 
    trigger:
      - platform: state
        entity_id: device_tracker.edgeos_jacqueline
        to: 'home'
    condition:
      - condition: time
        after: "07:30:00"
        before: "08:30:00"
        weekday:
          - "wed"
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.arnoud_status
            state: "Weg"
          - condition: state
            entity_id: input_select.arnoud_status
            state: "Net Weg"
    action:
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.ha_alarm
          code: !secret alarm_code
      - service: input_boolean.turn_on
        entity_id: input_boolean.cleaningmode
      - service: tts.google_say
        entity_id: media_player.huiskamer_speaker
        data:
          message: 'Goedemorgen jacqueline'
          language: 'nl'
      - delay:
          seconds: 5
      - service: spotcast.start
        data:
          entity_id: media_player.speakerfancy
          uri: 'spotify:playlist:37i9dQZF1DXbkk7Hqpo679'
          shuffle: true
          start_volume: 40
          random_song: true
      - wait_for_trigger:
          platform: state
          entity_id: device_tracker.edgeos_jacqueline
          to: 'away'
          for: '00:15:00'
        timeout: "04:00:00"
      - service: input_boolean.turn_off
        entity_id: input_boolean.cleaningmode
      - service: media_player.turn_off
        target:
          entity_id: media_player.speakerfancy
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.ha_alarm

script:
  cleaningmode_on:
    sequence:
      - service: light.turn_on
        entity_id: light.computer, light.hal, light.sk_ceiling, light.staande_lamp, light.eetkamer
        data:
          color_name: white
          brightness_pct: 100
          transition: 15
      - service: light.turn_on
        entity_id: light.keuken, light.trap_hal, light.overloop, light.sk_spot
        data:
          color_temp: 153
          brightness_pct: 100
          transition: 15
  cleaningmode_off:
    sequence:
      - service: light.turn_on
        entity_id: light.computer, light.hal, light.sk_ceiling, light.staande_lamp, light.eetkamer, light.keuken, light.trap_hal, light.overloop, light.sk_spot
        data:
          color_temp: 153
          brightness_pct: 50
          transition: 15
      - service: light.turn_off
        entity_id: light.computer, light.hal, light.sk_ceiling, light.staande_lamp, light.eetkamer, light.keuken, light.trap_hal, light.overloop, light.sk_spot
