input_boolean:
  cleaningmode:
    name: cleaning mode
automation:
  - alias: 'cleaning mode on'
    id: '0643587777777738989'
    trigger:
      - platform: state
        entity_id: input_boolean.cleaningmode
        to: 'on'
    action:
      - service: script.cleaningmode_on
  - alias: 'cleaning mode off'
    id: '6753290123480'
    trigger:
      - platform: state
        entity_id: input_boolean.cleaningmode
        to: 'off'
    action:
      - service: script.cleaningmode_off
  - alias: 'hue dimmer switch on'
    id: '167521365098632509816235'
    trigger: 
      - platform: state
        entity_id: sensor.0x0017880102e1e3b4_action
        to: 'on-press'
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.cleaningmode
  - alias: 'hue dimmer switch off'
    id: '87504935709864210938'
    trigger: 
      - platform: state
        entity_id: sensor.0x0017880102e1e3b4_action
        to: 'off-press'
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.cleaningmode
  - alias: 'jacqueline-binnen'
    id: 142c8938-9513-48fe-9345-01f55a7992a9 
    trigger:
      - platform: state
        entity_id: device_tracker.edgeos_jacqueline
        to: 'home'
    condition:
      - condition: time
        after: "07:30:00"
        before: "08:30:00"
        weekday:
          - "wed"
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.arnoud_status
            state: "Weg"
          - condition: state
            entity_id: input_select.arnoud_status
            state: "Net Weg"
    action:
      - service: alarm_control_panel.alarm_disarm
        target:
          entity_id: alarm_control_panel.ha_alarm
        data:
          code: !secret alarm_code
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.cleaningmode
      - service: tts.google_say
        target:
          entity_id: media_player.huiskamer_hub
        data:
          message: 'Goedemorgen jacqueline'
          language: 'nl'
      - delay:
          seconds: 5
      - service: spotcast.start
        target:
          entity_id: media_player.speakerfancy
        data:
          uri: 'spotify:playlist:37i9dQZF1DXbkk7Hqpo679'
          shuffle: true
          start_volume: 40
          random_song: true
      - wait_for_trigger:
          platform: state
          entity_id: device_tracker.edgeos_jacqueline
          to: 'away'
          for: '00:15:00'
        timeout: "04:00:00"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.cleaningmode
      - service: media_player.turn_off
        target:
          entity_id: media_player.speakerfancy
      - service: alarm_control_panel.alarm_arm_away
        target:
          entity_id: alarm_control_panel.ha_alarm

script:
  cleaningmode_on:
    sequence:
      - service: scene.create
        data:
          scene_id: before_cleaning1
          snapshot_entities:
            - light.hue_lightstrip_plus_1
            - light.staande_lamp
            - light.hue_color_pendant_down_1
            - light.hue_color_pendant_up_1
            - light.computer
            - light.hal
            - light.zoldervoor
            - light.zolderachter
            - light.sk_ceiling
            - light.sk_duo_spot_1
            - light.sk_duo_spot_2
            - light.overloop
            - light.keuken_1
            - light.keuken_2
            - light.keuken_3
            - light.trap_hal
      - service: light.turn_on
        target:
          entity_id: light.lampen
      - service: scene.create
        data:
          scene_id: before_cleaning2
          snapshot_entities:
            - light.hue_lightstrip_plus_1
            - light.staande_lamp
            - light.hue_color_pendant_down_1
            - light.hue_color_pendant_up_1
            - light.computer
            - light.hal
            - light.zoldervoor
            - light.zolderachter
            - light.sk_ceiling
            - light.sk_duo_spot_1
            - light.sk_duo_spot_2
            - light.overloop
            - light.keuken_1
            - light.keuken_2
            - light.keuken_3
            - light.trap_hal
      - service: light.turn_on
        target:
          entity_id: 
            - light.computer
            - light.hal
            - light.sk_ceiling
            - light.staande_lamp
            - light.zoldervoor
            - light.zolderachter
            - light.keuken
        data:
          color_name: white
          brightness_pct: 100
          transition: 15
      - service: light.turn_on
        target:
          entity_id: 
            - light.trap_hal
            - light.overloop
            - light.sk_spot

        data:
          color_temp: 153
          brightness_pct: 100
          transition: 15
  cleaningmode_off:
    sequence:
      - service: scene.turn_on
        target:
          entity_id: scene.before_cleaning2
        data:
          transition: 2
      - service: scene.turn_on
        target:
          entity_id: scene.before_cleaning1
        data:
          transition: 2
