sensor:
  - platform: history_stats
    name: arnoud_at_home
    entity_id: device_tracker.467cfa38bbada1bf
    state: 'Home'
    type: ratio
    duration:
      days: 7
    end: "{{ now() }}"