sensor:
  - platform: history_stats
    name: arnoud_at_home
    entity_id: device_tracker.8877c83ae202869c
    state:
      - "home"
      - "parking"
    type: ratio
    duration:
      days: 7
    end: "{{ now() }}"
