sensor:
  - platform: history_stats
    name: arnoud_at_home
    entity_id: device_tracker.369ab83aade93883
    state: 'home'
    type: ratio
    duration:
      days: 7
    end: "{{ now() }}"