automation:
  - alias: "test event"
    id: "b1244327-cfe9-4b12-b0ca-117d950b9968"
    trigger:
      - platform: state
        entity_id: input_boolean.guests_boolean
    action:
      - event: LOGBOOK_ENTRY
        event_data:
          name: Paulus
          message: is waking up
          entity_id: input_boolean.guests_boolean
          domain: light
