automation:
  - alias: 'turn off espressomaker when away'
    id: '678328023792301'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_select.arnoud_status
        to: 'Weg'
    action:
#      - service: switch.turn_off
#        data:
#          entity_id: switch.espressomaker
      - service: switch.turn_off
        data:
          entity_id: switch.0x7cb03eaa0a02be43_switch
  - alias: 'turn off esspresso maker'
    id: '1529161972987'
    hide_entity: true
    trigger:
    - at: '21:00:00'
      platform: time
    condition: []
    action:
#      - service: switch.turn_off
#        data:
#          entity_id: switch.espressomaker
      - service: switch.turn_off
        data:
          entity_id: switch.0x7cb03eaa0a02be43_switch
  - alias: 'Turn on espresso  maker'
    id: '1529161700562'
    hide_entity: true
    trigger:
    - at: ' 07:00:00' 
      platform: time
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.arnoud_status
            state: 'Net Thuis'
          - condition: state
            entity_id: input_select.arnoud_status
            state: 'Thuis'
    action:
#      - service: switch.turn_on
#        data:
#          entity_id: switch.espressomaker 
      - service: switch.turn_on
        data:
          entity_id: switch.0x7cb03eaa0a02be43_switch

  - alias: 'Turn on espresso maker (afternoon)'
    id: '1529161701532'
    hide_entity: true
    trigger:
      - platform: time
        at: '17:30:00' 
      - platform: state
        entity_id: input_select.arnoud_status
        to: 'Net Thuis'
    condition:
     condition: and
     conditions:
      - condition: time
        after: '17:30:00'
        before: '20:00:00'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.arnoud_status
            state: 'Net Thuis'
          - condition: state
            entity_id: input_select.arnoud_status
            state: 'Thuis'
    action:
#      - service: switch.turn_on
#        data:
#          entity_id: switch.espressomaker 
      - service: switch.turn_on
        data:
          entity_id: switch.0x7cb03eaa0a02be43_switch