automation:
  - alias: "turn off espressomaker"
    id: "678328023792301"
    trigger:
#      - platform: template
#        value_template: "{{ is_state('input_select.house_mode', 'weg') }}"
      - platform: state
        entity_id: schedule.espresso
        to: "off"
      - platform: numeric_state
        entity_id: zone.home
        below: 1
        for: 
          minutes: 10
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.esspresso
#  - alias: "turn off esspresso maker"
#    id: "1529161972987"
#    trigger:
#      - at: "21:00:00"
#        platform: time
#    action:
#      - service: switch.turn_off
#        target:
#          entity_id: switch.esspresso
#  - alias: "Turn on espresso  maker"
#    id: "1529161700562"
#    trigger:
#      - at: "07:30:00"
#        platform: time
#    condition: "{{ not is_state('input_select.house_mode', 'weg') }}"
#    action:
#      - service: switch.turn_on
#        target:
#          entity_id: switch.esspresso

  - alias: "Turn on espresso maker (afternoon)"
    id: "1529161701532"
    trigger:
#      - platform: time
#        at: "19:00:00"
      - platform: state
        entity_id: schedule.espresso
        to: "on"
#      - platform: state
#        entity_id: input_select.arnoud_status
#        to: "Net Thuis"
      - platform: numeric_state
        entity_id: zone.home
        above: 0
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:
            - schedule.espresso
          state: "on"
        - condition: numeric_state
          entity_id:
            - zone.home
          above: 0

#        - condition: time
#          after: "19:00:00"
#          before: "20:30:00"
#        - condition: or
#          conditions:
#            - alias: "arnoud thuis"
#              condition: state
#              entity_id: input_select.arnoud_status
#             state: "Thuis"
#            - alias: "arnoud net thuis"
#              condition: state
#              entity_id: input_select.arnoud_status
#              state: "Net Thuis"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.esspresso
