automation:
  - alias: "turn off espressomaker"
    id: "678328023792301"
    trigger:
      - trigger: state
        entity_id: schedule.espresso
        to: "off"
      - trigger: numeric_state
        entity_id: zone.home
        below: 1
        for:
          minutes: 10
    action:
      - action: switch.turn_off
        target:
          entity_id: switch.shellyplugsg3_espresso
  - alias: "Turn on espresso maker"
    id: "1529161701532"
    trigger:
      - trigger: state
        entity_id: schedule.espresso
        to: "on"
      - trigger: state
        entity_id: schedule.espresso_vacation
        to: "on"
      - trigger: numeric_state
        entity_id: zone.home
        above: 0
    condition:
      - condition: numeric_state
        entity_id:
          - zone.home
        above: 0
    action:
      - choose:
        - conditions:
            - condition: state
              entity_id: schedule.espresso
              state: "on"
            - condition: state
              entity_id: binary_sensor.workday_sensor_mod
              state: "on"
          sequence:
            - repeat:
                sequence:
                  - action: switch.turn_on
                    target:
                      entity_id: switch.shellyplugsg3_espresso
                  - delay:
                      seconds: 60
                until:
                  - condition: state
                    entity_id: switch.shellyplugsg3_espresso
                    state: "on"
        - conditions:
            - condition: state
              entity_id: schedule.espresso_vacation
              state: "on"
            - condition: state
              entity_id: binary_sensor.workday_sensor_mod
              state: "off"
          sequence:
            - repeat:
                sequence:
                  - action: switch.turn_on
                    target:
                      entity_id: switch.shellyplugsg3_espresso
                  - delay:
                      seconds: 60
                until:
                  - condition: state
                    entity_id: switch.shellyplugsg3_espresso
                    state: "on"
