automation:
  - alias: "turn off espressomaker"
    id: "678328023792301"
    trigger:
      - platform: state
        entity_id: schedule.espresso
        to: "off"
      - platform: numeric_state
        entity_id: zone.home
        below: 1
        for: 
          minutes: 10
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.esspresso
  - alias: "Turn on espresso maker"
    id: "1529161701532"
    trigger:
      - platform: state
        entity_id: schedule.espresso
        to: "on"
      - platform: numeric_state
        entity_id: zone.home
        above: 0
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:
            - schedule.espresso
          state: "on"
        - condition: numeric_state
          entity_id:
            - zone.home
          above: 0
    action:
      - repeat:
          sequence:
            - service: switch.turn_on
              target:
                entity_id: switch.esspresso
            - delay:
                seconds: 60
          until:
            - condition: state
              entity_id: switch.esspresso
              state: "on"
