input_text:
  here_api:
    initial: !secret here_api
sensor:
#  - platform: google_travel_time
#    scan_interval: 1800
#    name: Phone To Home
#    api_key: !secret google_apikey
#    origin: device_tracker.4dd0404d
#    destination: zone.home
#  - platform: google_travel_time
#    scan_interval: 600
#    name: Home to ING
#    api_key: !secret google_apikey
#    origin: zone.home
#    destination: zone.ING
#  - platform: google_travel_time
#    scan_interval: 600
#    name: ING to Home
#    api_key: !secret google_apikey
#    origin: zone.ING
#    destination: zone.home 
#  - platform: google_travel_time
#    scan_interval: 900
#    api_key: !secret google_apikey
#    origin: device_tracker.467cfa38bbada1bf
#    destination: sensor.cal_location
#    name: google_travel_time_driving
#  - platform: google_travel_time
#    scan_interval: 900
#    api_key: !secret google_apikey
#    origin: zone.home
#    destination: sensor.cal_location_alarm
#    name: google_travel_time_alarm
# Example configuration.yaml entry

  - platform: rest
    resource_template: https://geocode.search.hereapi.com/v1/geocode?q={{states('sensor.cal_location_alarm')|regex_replace(find='[0-9]{4}(| )[A-Z]{2} *', replace='', ignorecase=False)|urlencode}}&apiKey={{states('input_text.here_api')}}
    value_template: "{{(value_json['items'][0]['position']['lat']|string ) + ',' + (value_json['items'][0]['position']['lng'] |string)}}"
    name: "alarm_latlong"

  - platform: here_travel_time
    api_key: !secret here_api
    origin_entity_id: zone.home
    destination_entity_id: sensor.alarm_latlong
    name: here_travel_time_alarm
  - platform: here_travel_time
    api_key: !secret here_api
    origin_entity_id: zone.home
    destination_entity_id: sensor.alarm_latlong
    name: here_travel_time_alarm_bike
    mode: bicycle
  - platform: here_travel_time
    api_key: !secret here_api
    origin_entity_id: zone.home
    destination_entity_id: sensor.cal_location
    name: here_travel_time
  - platform: statistics
    unique_id: 74d05bf9-e853-4bd5-ba16-e03536bad0c8""
    entity_id: sensor.ing_to_home
    name: ing_to_home_stats
    sampling_size: 288
    state_characteristic: mean
  - platform: statistics
    unique_id: "568671b2-86fa-4c24-b6c1-9c7e6b1ec444"
    entity_id: sensor.home_to_ing
    name: home_to_ing_stats
    sampling_size: 288
    state_characteristic: mean

template:
  - sensor:
    - name: "calc_travel_time"
      unique_id: "d0efa819-5eab-4c5d-993f-95d03ccb0b99"
      state: >
        {% set duration = state_attr("sensor.google_travel_time_driving", "duration") %}
        {%if duration == None %}
          0
        {% else %}
          {%if duration.split(" ")[2]==Null %}
            {{ duration.split(" ")[0] | int * 60 }}
          {% else %}
            {{ duration.split(" ")[0] | int *3600 + duration.split(" ")[2] | int *60}}
          {% endif %}
        {% endif %}
    - name: "google_api_key"
      unique_id: "a68c6663-094f-405d-b625-9eb104cd988f"
      state: !secret google_apikey