#googlehome:
#  devices:
#   - host: 192.168.1.194
#     track_alarms: true
#     track_devices: false
#   - host: 192.168.1.132
#     track_alarms: true
#     track_devices: false
#   - host: 192.168.1.239
#     track_alarms: true
#     track_devices: false
google_assistant:
  project_id: moonlit-helper-211706
  #  api_key: !secret google_apikey
  service_account: !include 27024-e0aec8e9f7d0.json
  #  expose_by_default: false
  #  exposed_domains:
  #    - group
  #    - scene
  #    - script
  #    - switch
  #    - fan
  #    - media_player
  #    - lock
  #    - cover
  #    - climate
  #    - vacuum
  entity_config:
    input_boolean.wakeuplight_automatic:
      expose: false
    input_boolean.wakeuplight_manual:
      expose: false
    media_player.slaapkamer_speaker:
      expose: false
    media_player.huiskamer_speaker:
      expose: false
    media_player.ht_nt5:
      expose: false
    media_player.ht_nt5_surround:
      expose: false
    media_player.studeerkamer_speaker:
      expose: false
    media_player.huiskamer_tv:
      expose: false
    media_player.slaapkamer_tv:
      expose: false



automation:
  - alias: 'melding nieuw alarm'
    id: '7480949648104893'
    trigger:
      - platform: state
        entity_id: 
            - sensor.slaapkamer_speaker_alarms
            - sensor.huiskamer_speaker_alarms
            - sensor.studeerkamer_speaker_alarms
            - sensor.slaapkamer_speaker_timers
            - sensor.huiskamer_speaker_timers
            - sensor.studeerkamer_speaker_timers
    action:
      - condition: "{{ states(trigger.entity_id) != 'unavailable' }}"
      - service: notify.pushover
        data:
          message: "Nieuw alarm gezet om {{as_timestamp(states(trigger.entity_id )) | timestamp_local}}"
          title: 'Nieuw google home alarm'

