input_text:
  here_api:
    initial: !secret here_api
  home_address:
    initial: !secret home_address
sensor:
#  - platform: google_travel_time
#    scan_interval: 1800
#    name: Phone To Home
#    api_key: !secret google_apikey
#    origin: device_tracker.4dd0404d
#    destination: zone.home
#  - platform: google_travel_time
#    scan_interval: 600
#    name: Home to ING
#    api_key: !secret google_apikey
#    origin: zone.home
#    destination: zone.ING
#  - platform: google_travel_time
#    scan_interval: 600
#    name: ING to Home
#    api_key: !secret google_apikey
#    origin: zone.ING
#    destination: zone.home 
#  - platform: google_travel_time
#    scan_interval: 900
#    api_key: !secret google_apikey
#    origin: device_tracker.467cfa38bbada1bf
#    destination: sensor.cal_location
#    name: google_travel_time_driving
#  - platform: google_travel_time
#    scan_interval: 900
#    api_key: !secret google_apikey
#    origin: zone.home
#    destination: sensor.cal_location_alarm
#    name: google_travel_time_alarm
# Example configuration.yaml entry

  - platform: rest
    resource_template: https://geocode.search.hereapi.com/v1/geocode?q={{states('sensor.cal_location_alarm')|regex_replace(find='[0-9]{4}(| )[A-Z]{2} *', replace='', ignorecase=False)|urlencode}}&apiKey={{states('input_text.here_api')}}
    value_template: "{{ now() }}"
    json_attributes_path: "items.0.position"
    json_attributes:
      - lng
      - lat
    name: "alarm_latlong"
    scan_interval: 900
  - platform: rest
    resource_template: https://geocode.search.hereapi.com/v1/geocode?q={{states('sensor.cal_location')|regex_replace(find='[0-9]{4}(| )[A-Z]{2} *', replace='', ignorecase=False)|urlencode}}&apiKey={{states('input_text.here_api')}}
    value_template: "{{ now() }}"
    json_attributes_path: "items.0.position"
    json_attributes:
      - lng
      - lat
    name: "afspraak_latlong"
    scan_interval: 900
#  - platform: here_travel_time
#    api_key: !secret here_api
#    origin_entity_id: zone.home
#    destination_entity_id: sensor.alarm_latlong_mod
#    name: here_travel_time_alarm
#    scan_interval: 900
#    traffic_mode: true
#  - platform: here_travel_time
#    api_key: !secret here_api
#    origin_entity_id: zone.home
#    destination_entity_id: sensor.alarm_latlong_mod
#    name: here_travel_time_alarm_bike
#    mode: bicycle
#    scan_interval: 900
#  - platform: here_travel_time
#    api_key: !secret here_api
#    origin_entity_id: person.arnoud
#    destination_entity_id: sensor.afspraak_latlong_mod
#    name: here_travel_time
#    scan_interval: 900
#    traffic_mode: true
#  - platform: here_travel_time
#    api_key: !secret here_api
#    origin_entity_id: person.arnoud
#    destination_entity_id: sensor.afspraak_latlong_mod
#    name: here_travel_time_bike
#    mode: bicycle
#    scan_interval: 900
    
template:
  - sensor:
    - name: "calc_travel_time"
      unique_id: "d0efa819-5eab-4c5d-993f-95d03ccb0b99"
      state: >
        {% set duration = state_attr("sensor.google_travel_time_driving", "duration") %}
        {%if duration == None %}
          0
        {% else %}
          {%if duration.split(" ")[2]==Null %}
            {{ duration.split(" ")[0] | int * 60 }}
          {% else %}
            {{ duration.split(" ")[0] | int *3600 + duration.split(" ")[2] | int *60}}
          {% endif %}
        {% endif %}
    - name: "calc_travel_time_alarm"
      unique_id: "95f95923-34f8-4a25-b3fa-696884a37611"
      state: >
        {% set duration = state_attr("sensor.google_travel_time_alarm", "duration") %}
        {%if duration == None %}
          0
        {% else %}
          {%if duration.split(" ")[2]==Null %}
            {{ duration.split(" ")[0] | int * 60 }}
          {% else %}
            {{ duration.split(" ")[0] | int *3600 + duration.split(" ")[2] | int *60}}
          {% endif %}
        {% endif %}
    - name: "google_api_key"
      unique_id: "a68c6663-094f-405d-b625-9eb104cd988f"
      state: !secret google_apikey
    - name: "alarm_latlong_mod"
      state: "{{states('sensor.alarm_latlong')}}"
      attributes:
        latitude: "{{iif(state_attr('sensor.alarm_latlong', 'lat') == None, 0, state_attr('sensor.alarm_latlong', 'lat')|float)}}"
        longitude: "{{iif(state_attr('sensor.alarm_latlong', 'lng') == None, 0, state_attr('sensor.alarm_latlong', 'lng')|float)}}"
    - name: "afspraak_latlong_mod"
      state: "{{states('sensor.afspraak_latlong')}}"
      attributes:
        latitude: "{{iif(state_attr('sensor.afspraak_latlong', 'lat') == None, 0, state_attr('sensor.afspraak_latlong', 'lat')|float)}}"
        longitude: "{{iif(state_attr('sensor.afspraak_latlong', 'lng') == None, 0, state_attr('sensor.afspraak_latlong', 'lng')|float)}}"