#googlehome:
#  devices:
#   - host: 192.168.1.194
#     track_alarms: true
#     track_devices: false
#   - host: 192.168.1.132
#     track_alarms: true
#     track_devices: false
#   - host: 192.168.1.239
#     track_alarms: true
#     track_devices: false
google_assistant:
  project_id: moonlit-helper-211706
  #  api_key: !secret google_apikey
  service_account: !include 27024-e0aec8e9f7d0.json
  #  expose_by_default: false
  #  exposed_domains:
  #    - group
  #    - scene
  #    - script
  #    - switch
  #    - fan
  #    - media_player
  #    - lock
  #    - cover
  #    - climate
  #    - vacuum
  entity_config:
    input_boolean.wakeuplight_automatic:
      expose: false
    input_boolean.wakeuplight_manual:
      expose: false
    media_player.paar_studeerkamer:
      expose: false
    media_player.huiskamer_hub:
      expose: false
    media_player.ht_nt5:
      expose: false
    media_player.ht_nt5_surround:
      expose: false
    media_player.studeerkamer_speaker:
      expose: false
    media_player.huiskamer_tv:
      expose: false
    media_player.slaapkamer_tv:
      expose: false
    media_player.studeerkamer_speaker_l:
      expose: false
    media_player.studeerkamer_speaker_r:
      expose: false

automation:
  - alias: "melding nieuw alarm"
    id: "7480949648104893"
    trigger:
      - platform: state
        entity_id: 
            - sensor.slaapkamer_speaker_alarms
            - sensor.huiskamer_hub_alarms
            - sensor.studeerkamer_speaker_alarms
            - sensor.slaapkamer_speaker_timers
            - sensor.huiskamer_hub_timers
            - sensor.studeerkamer_speaker_timers
    action:
      - condition: "{{ states(trigger.entity_id) != 'unavailable' and states(trigger.entity_id) != None }}"
      - service: notify.pushover
        data:
          message: "Nieuw alarm gezet om {{as_timestamp(states(trigger.entity_id )) | timestamp_local}}"
          title: "Nieuw google home alarm"
  - id: "1651157537171"
    alias: cast dashboard to hub when idle
    description: ""
    trigger:
    - platform: device
      device_id: b4516adcd2d3f9f786af8bd19d53201c
      domain: media_player
      entity_id: media_player.huiskamer_hub
      type: idle
      for:
        hours: 0
        minutes: 0
        seconds: 30
    - platform: device
      device_id: b4516adcd2d3f9f786af8bd19d53201c
      domain: media_player
      entity_id: media_player.huiskamer_hub
      type: turned_off
      for:
        hours: 0
        minutes: 0
        seconds: 30
    condition: []
    action:
    - service: cast.show_lovelace_view
      data:
        entity_id: media_player.huiskamer_hub
        dashboard_path: lovelace-nest
        view_path: home
    mode: single
  - id: "33ae710c-2f29-4a76-a922-bb5f9732dd5a"
    alias: "stop google hub cast so view mode can switch to and from dark mode"
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 0
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: 0
    action:
      - service: media_player.media_stop
        data: {}
        target:
          device_id: b4516adcd2d3f9f786af8bd19d53201c
    mode: single