proximity:
  home2:
    devices:
      - sensor.iss
    unit_of_measurement: km
camera:
  - platform: generic
    name: iss
    still_image_url: "https://maps.googleapis.com/maps/api/staticmap?key={{states('sensor.google_api_key')}}&center={{state_attr('sensor.iss', 'latitude')}},{{state_attr('sensor.iss', 'longitude')}}&zoom=6&size=600x300&maptype=hybrid&markers=color:blue%7Clabel:ISS%7C{{state_attr('sensor.iss', 'latitude')}},{{state_attr('sensor.iss', 'longitude')}}"
    limit_refetch_to_url_change: true

sensor:
  - platform: rest
    resource: https://api.wheretheiss.at/v1/satellites/25544
    name: iss
    verify_ssl: true
    value_template: "{{ value_json.timestamp }}"
    json_attributes:
      - longitude
      - latitude
      - altitude
  - platform: template
    sensors:
      iss_altitude:
        value_template: "{{state_attr('sensor.iss', 'altitude') | round | int}}"
        unit_of_measurement: "Km"
      iss_latitude:
        value_template: "{state_attr('sensor.iss', 'latitude') | float}}"
        unit_of_measurement: "°"
      iss_longitude:
        value_template: "{{state_attr('sensor.iss', 'longitude') | float}}"
        unit_of_measurement: "°"
      iss_horizon:
        value_template: "{{(sqrt( (2 * 6371 * state_attr('sensor.iss', 'altitude')) + state_attr('sensor.iss', 'altitude')**2)  + sqrt( (2 * 6371 * (2/1000))+ (2/1000)**2)) | round | int }}"
        unit_of_measurement: "Km"
      iss_distance:
        value_template: "{{distance(state_attr('sensor.iss', 'latitude'), state_attr('sensor.iss', 'longitude')) | round | int}}"
        unit_of_measurement: "Km"
      iss_visible:
        value_template: >-
          {%if  state_attr('sun.sun', 'elevation')  < -6  and state_attr('sun.sun', 'elevation') > -18 %}
            {{ states('sensor.iss_distance') < states('sensor.iss_horizon') }}
          {% else %}
            False   
          {% endif %}
automation:
  - alias: "ISS in range"
    id: "130256743518934101213"
    trigger:
      platform: template
      value_template: "{{states('proximity.home2') < states('sensor.iss_horizon')}}"
    condition:
      condition: and
      conditions:
        - "{{ state_attr('proximity.home2', 'dir_of_travel') == 'towards' }}"
        - "{{is_state('sensor.iss_visible', 'True')}}"
    action:
      service: notify.pushover
      data:
        message: "ISS is nu {{states('proximity.home2')}} Km ver en komt dichterbij"
        title: "ISS"
        data:
          priority: -1
          url: "https://foto-album.duckdns.org/lovelace/iss"
