
#camera:
#  - platform: generic
#    name: iss
#    still_image_url: "{{'https://maps.googleapis.com/maps/api/staticmap?key=' + states('sensor.google_api_key') + '&center=' + state_attr('binary_sensor.iss', 'latitude')|string + ',' + state_attr('binary_sensor.iss', 'longitude')|string + '&zoom=6&size=600x300&maptype=hybrid&markers=color:blue%7Clabel:ISS%7C' + state_attr('sensor.iss', 'latitude')|string + ',' + state_attr('sensor.iss', 'longitude')|string}}"
#    limit_refetch_to_url_change: true

sensor:
  - platform: rest
    resource: https://api.wheretheiss.at/v1/satellites/25544
    name: iss
    unique_id: "6ff0f7d9-0338-4fd2-b835-728692c7acd1"
    verify_ssl: true
    value_template: "{{ value_json.timestamp }}"
    json_attributes:
      - longitude
      - latitude
      - altitude
      - visibility
      - footprint
      - solar_lat
      - solar_lon

template:
  - sensor:
    - name: "iss_altitude"
      unique_id: "381b9b1d-c09a-4856-9ee1-a525c8891a5e"
      state: "{{state_attr('sensor.iss', 'altitude') | round | int}}"
      unit_of_measurement: "Km"
    - name: "iss_latitude"
      unique_id: "761348ef-9b85-415d-b983-687f6abe7fa2"
      state: "{{state_attr('sensor.iss', 'latitude') | float}}"
      unit_of_measurement: "°"
    - name: "iss_longitude"
      unique_id: "668b19c8-b0e8-4ed1-a9da-21894f3885ee"
      state: "{{state_attr('sensor.iss', 'longitude') | float}}"
      unit_of_measurement: "°"
    - name: "iss_horizon"
      unique_id: "8d6866e6-2cab-47b8-957f-e5ec3a9049f5"
      state: "{{(sqrt( (2 * 6371 * state_attr('sensor.iss', 'altitude')) + state_attr('sensor.iss', 'altitude')**2)  + sqrt( (2 * 6371 * (2/1000))+ (2/1000)**2)) | round | int }}"
      unit_of_measurement: "Km"
    - name: "iss_distance"
      unique_id: "fe078b48-56ca-409b-9a2c-ad6a2a65106f"
      state: "{{distance(state_attr('sensor.iss', 'latitude'), state_attr('sensor.iss', 'longitude')) | round | int}}"
      unit_of_measurement: "Km"
    - name: "iss_visible"
      unique_id: "73cb79cd-b244-4772-95af-20eb27ffc06d"
      state: >-
        {%if  state_attr('sun.sun', 'elevation')  < -6  and state_attr('sun.sun', 'elevation') > -18 %}
          {{ (states('sensor.iss_distance')|int) < (states('sensor.iss_horizon')|int) }}
        {% else %}
          False   
        {% endif %}
    - name: "iss_elevation"
      unique_id: "197c566f-23c0-4ef6-a832-ff97f9ca281c"
      state: "{{state_attr('sensor.iss_alt_az', 'altitude')|float|round(1)}}"
      unit_of_measurement: "°"
    - name: "iss_visibility"
      unique_id: "cf2acaf1-ddf6-4496-a6b5-3ef83e8328a5"
      state: "{{state_attr('sensor.iss', 'visibility')}}"
automation:
  - alias: "ISS in range"
    id: "130256743518934101213"
    trigger:
      platform: numeric_state
      entity_id: sensor.iss_alt_az
      attribute: altitude
      above: 5.0
    condition: "{{state_attr('sun.sun', 'elevation')  < -6  and state_attr('sun.sun', 'elevation') > -18}}"
    action:
      - variables:
          iss_direction: >
            {% set azimuth = state_attr('sensor.iss_alt_az', 'azimuth')|float %}
            {% if azimuth > 348.75 or azimuth <= 11.25 %}
              Noordelijke
            {% elif azimuth > 11.25 and azimuth <= 33.75 %}
              Noord-noordoostelijke
            {% elif azimuth > 33.75 and azimuth <= 56.25 %}
              Noordoostelijke
            {% elif azimuth > 56.25 and azimuth <= 78.75 %}
              Oost-Noordoostelijke
            {% elif azimuth > 78.25 and azimuth <= 101.25 %}
              Oostelijke
            {% elif azimuth > 101.25 and azimuth <= 123.75 %}
              Oost-zuidoostelijke
            {% elif azimuth > 123.75 and azimuth <= 146.25 %}
              Zuidoostelijke
            {% elif azimuth > 146.25 and azimuth <= 168.75 %}
              Zuid-zuidoostelijke
            {% elif azimuth > 168.75 and azimuth <= 191.25 %}
              Zuidelijke
            {% elif azimuth > 191.25 and azimuth <= 213.75 %}
              Zuid-zuidwestelijke
            {% elif azimuth > 213.75 and azimuth <= 236.25 %}
              Zuidwestelijke
            {% elif azimuth > 236.25 and azimuth <= 258.75 %}
              West-Zuidwestelijke
            {% elif azimuth > 258.75 and azimuth <= 281.25 %}
              Westelijke
            {% elif azimuth > 281.25 and azimuth <= 303.75 %}
              West-Noordwestelijke
            {% elif azimuth > 303.75 and azimuth <= 326.25 %}
              Noordwestelijke
            {% elif azimuth > 326.25 and azimuth <= 348.75 %}
              Noord-noordwestelijke
            {% else %}
              Onbekende
            {% endif %}
      - service: notify.pushover
        data:
          message: "Het ISS is nu {{state_attr('sensor.iss_alt_az', 'distkm')|int}} Km ver en {{state_attr('sensor.iss_alt_az', 'altitude')|round(1)}} graden boven de horizon in {{iss_direction}} richting "
          title: "ISS"
          data:
            priority: 0
            url: "https://foto-album.duckdns.org/lovelace/iss"
      - condition: and
        conditions:
          - condition: state
            entity_id: person.arnoud
            state: "home"
          - condition: state
            entity_id:
              - schedule.tts_announce
            state: "on"
          - alias: "no clouds"
            condition: numeric_state
            entity_id: sensor.astroweather_cloudless
            above: 75
      - alias: "Send TTS using Google Home Resume script"
        service: script.turn_on
        target:
          entity_id: script.google_home_resume
        data:
          variables:
            action:
              - action: tts.speak
                target:
                  entity_id: tts.home_assistant_cloud
                data:
                  cache: false
                  media_player_entity_id: media_player.speakers
                  language: nl-NL
                  message: "ISS is nu {{state_attr('sensor.iss_alt_az', 'altitude')|round(1)}} graden boven de horizon in {{iss_direction}} richting "
      - alias: "Wait until the target is idle or off before applying the volume for the TTS message"
        wait_template: "{{ states('media_player.speakers') in ['idle', 'off'] }}"
      - alias: "Apply TTS volume"
        service: media_player.volume_set
        target:
          entity_id: media_player.speakers
        data:
          volume_level: "{{states('input_number.tts_volume')| float}}"
          
  - alias: "update alt_az sensor"
    id: "6b87ea2d-ff66-4d86-9b9f-123b171e2f99"
    trigger:
      platform: state
      entity_id: sensor.iss
    action:
      service: python_script.iss
      data: {}

