proximity:
  home2:
    devices:
      - sensor.iss
    unit_of_measurement: km
camera:
  - platform: generic
    name: iss
    still_image_url: "https://maps.googleapis.com/maps/api/staticmap?key={{states('sensor.google_api_key')}}&center={{state_attr('binary_sensor.iss', 'latitude')}},{{state_attr('binary_sensor.iss', 'longitude')}}&zoom=6&size=600x300&maptype=hybrid&markers=color:blue%7Clabel:ISS%7C{{state_attr('sensor.iss', 'latitude')}},{{state_attr('sensor.iss', 'longitude')}}"
    limit_refetch_to_url_change: true

sensor:
  - platform: rest
    resource: https://api.wheretheiss.at/v1/satellites/25544
    name: iss
    verify_ssl: true
    value_template: "{{ value_json.timestamp }}"
    json_attributes:
      - longitude
      - latitude
      - altitude
      - visibility
      - footprint
      - solar_lat
      - solar_lon

template:
  - sensor:
    - name: "iss_altitude"
      unique_id: "381b9b1d-c09a-4856-9ee1-a525c8891a5e"
      state: "{{state_attr('sensor.iss', 'altitude') | round | int}}"
      unit_of_measurement: "Km"
    - name: "iss_latitude"
      unique_id: "761348ef-9b85-415d-b983-687f6abe7fa2"
      state: "{{state_attr('sensor.iss', 'latitude') | float}}"
      unit_of_measurement: "°"
    - name: "iss_longitude"
      unique_id: "668b19c8-b0e8-4ed1-a9da-21894f3885ee"
      state: "{{state_attr('sensor.iss', 'longitude') | float}}"
      unit_of_measurement: "°"
    - name: "iss_horizon"
      unique_id: "8d6866e6-2cab-47b8-957f-e5ec3a9049f5"
      state: "{{(sqrt( (2 * 6371 * state_attr('sensor.iss', 'altitude')) + state_attr('sensor.iss', 'altitude')**2)  + sqrt( (2 * 6371 * (2/1000))+ (2/1000)**2)) | round | int }}"
      unit_of_measurement: "Km"
    - name: "iss_distance"
      unique_id: "fe078b48-56ca-409b-9a2c-ad6a2a65106f"
      state: "{{distance(state_attr('sensor.iss', 'latitude'), state_attr('sensor.iss', 'longitude')) | round | int}}"
      unit_of_measurement: "Km"
    - name: "iss_visible"
      unique_id: "73cb79cd-b244-4772-95af-20eb27ffc06d"
      state: >-
        {%if  state_attr('sun.sun', 'elevation')  < -6  and state_attr('sun.sun', 'elevation') > -18 %}
          {{ (states('sensor.iss_distance')|int) < (states('sensor.iss_horizon')|int) }}
        {% else %}
          False   
        {% endif %}
    - name: "iss_elevation"
      unique_id: "197c566f-23c0-4ef6-a832-ff97f9ca281c"
      state: "{{state_attr('sensor.iss_alt_az', 'altitude')|float|round(1)}}"
      unit_of_measurement: "°"
    - name: "iss_visibility"
      unique_id: "cf2acaf1-ddf6-4496-a6b5-3ef83e8328a5"
      state: "{{state_attr('sensor.iss', 'visibility')}}"
automation:
  - alias: "ISS in range"
    id: "130256743518934101213"
    trigger:
      platform: numeric_state
      entity_id: sensor.iss_alt_az
      attribute: altitude
      above: 5.0
    condition: "{{state_attr('sun.sun', 'elevation')  < -6  and state_attr('sun.sun', 'elevation') > -18}}"
    action:
      service: notify.pushover
      data:
        message: >
          {% set azimuth = state_attr('sensor.iss_alt_az', 'azimuth')|float %}
          {% if azimuth > 348.75 or azimuth <= 11.25 %}
            {% set direction = 'N' %}
          {% elif azimuth > 11.25 and azimuth <= 33.75 %}
            {% set direction = 'NNE' %}
          {% elif azimuth > 33.75 and azimuth <= 56.25 %}
            {% set direction = 'NE' %}
          {% elif azimuth > 56.25 and azimuth <= 78.75 %}
            {% set direction = 'ENE' %}
          {% elif azimuth > 78.25 and azimuth <= 101.25 %}
            {% set direction = 'E' %}
          {% elif azimuth > 101.25 and azimuth <= 123.75 %}
            {% set direction = 'ESE' %}
          {% elif azimuth > 123.75 and azimuth <= 146.25 %}
            {% set direction = 'SE' %}
          {% elif azimuth > 146.25 and azimuth <= 168.75 %}
            {% set direction = 'SSE' %}
          {% elif azimuth > 168.75 and azimuth <= 191.25 %}
            {% set direction = 'S' %}
          {% elif azimuth > 191.25 and azimuth <= 213.75 %}
            {% set direction = 'SSW' %}
          {% elif azimuth > 213.75 and azimuth <= 236.25 %}
            {% set direction = 'SW' %}
          {% elif azimuth > 236.25 and azimuth <= 258.75 %}
            {% set direction = 'WSW' %}
          {% elif azimuth > 258.75 and azimuth <= 281.25 %}
            {% set direction = 'W' %}
          {% elif azimuth > 281.25 and azimuth <= 303.75 %}
            {% set direction = 'WNW' %}
          {% elif azimuth > 303.75 and azimuth <= 326.25 %}
            {% set direction = 'NW' %}
          {% elif azimuth > 326.25 and azimuth <= 348.75 %}
            {% set direction = 'NNW' %}
          {% else %}
            {% set direction = '' %}
          {% endif %}
          ISS is nu {{state_attr('sensor.iss_alt_az', 'distkm')|int}} Km ver en {{state_attr('sensor.iss_alt_az', 'altitude')|round(1)}} graden boven de horizon in {{direction}} richting 
        title: "ISS"
        data:
          priority: -1
          url: "https://foto-album.duckdns.org/lovelace/iss"
  - alias: "update alt_az sensor"
    id: "6b87ea2d-ff66-4d86-9b9f-123b171e2f99"
    trigger:
      platform: state
      entity_id: sensor.iss
    action:
      service: python_script.iss
      data: {}

