automation:
  - alias: 'Lights on normal'
    id: '1528911899317' 
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state.attributes.elevation }}"
        below: 3.5
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.woonkamer
          state: 'off'
        - condition: template
          value_template: "{{ not is_state('input_select.house_mode', 'weg') }}"
    action:
      - service: script.woonkamer_lights_fadein

  - alias: 'Lights on bad weather'
    id: '5312689562015890236985290'
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state.attributes.elevation }}"
        below: 7
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.woonkamer
          state: 'off'
        - condition: template
          value_template: "{{ not is_state('input_select.house_mode', 'weg') }}"
        # measurement newer then 30 minutes
        - condition: template
          value_template: "{{as_timestamp(strptime(state_attr('sensor.berkhout_condition', 'Measured'),'%a %b %d %H:%M:%S %Y'))+1800 > as_timestamp(now())}}"
        # sky not clear
        - condition: template
          value_template: "{{ not is_state('sensor.berkhout_condition', 'clear') }}"
    action:
      - service: script.woonkamer_lights_fadein



  - alias: 'Lights on thuiskomst'
    id: '5480797213460891' 
    trigger:
      - platform: state
        entity_id: input_select.arnoud_status
        to: 'Net Thuis'
    condition:
      condition: or
      conditions:
        - condition: and
          conditions:
            - condition: numeric_state
              entity_id: sun.sun
              value_template: "{{ state.attributes.elevation }}"
              below: 3.5
            - condition: state
              entity_id: group.woonkamer
              state: 'off'
        - condition: and
          conditions:
            - condition: state
              entity_id: group.woonkamer
              state: 'off'
            - condition: numeric_state
              entity_id: sun.sun
              value_template: "{{ state.attributes.elevation }}"
              below: 0
            # measurement newer then 30 minutes
            - condition: template
              value_template: "{{as_timestamp(strptime(state_attr('sensor.berkhout_condition', 'Measured'),'%a %b %d %H:%M:%S %Y'))+1800 > as_timestamp(now())}}"
            # sky not clear
            - condition: template
              value_template: "{{ not is_state('sensor.berkhout_condition', 'clear') }}"
    action:
      - service: script.woonkamer_lights


script:
  woonkamer_lights_fadein:
    sequence:
      - alias: staande lamp
        service: light.turn_on
        data:
          entity_id: light.staande_lamp
          brightness_pct: 1
          kelvin: 3000
      - alias: strip
        service: light.turn_on
        data:
          entity_id: light.hue_lightstrip_plus_1
          xy_color:
          - 0.3388
          - 0.1332
          brightness_pct: 1
      - alias: staande lamp
        service: light.turn_on
        data:
          entity_id: light.staande_lamp
          transition: 300
          brightness_pct: 50
          kelvin: 3000
      - alias: strip
        service: light.turn_on
        data:
          entity_id: light.hue_lightstrip_plus_1
          transition: 300
          xy_color:
          - 0.3388
          - 0.1332
          brightness_pct: 30
  woonkamer_lights:
    sequence:
      - alias: staande lamp
        service: light.turn_on
        data:
          entity_id: light.staande_lamp
          transition: 2
          brightness_pct: 50
          kelvin: 3000
      - alias: strip
        service: light.turn_on
        data:
          entity_id: light.hue_lightstrip_plus_1
          transition: 2
          xy_color:
          - 0.3388
          - 0.1332
          brightness_pct: 30
