light:
  - platform: group
    name: sk_spot
    entities:
      - light.sk_duo_spot_1
      - light.sk_duo_spot_2
  - platform: group
    name: keuken
    entities:
      - light.keuken_1
      - light.keuken_2
      - light.keuken_3
  - platform: group
    name: woonkamer
    entities:
      - light.hue_lightstrip_plus_1
      - light.staande_lamp
  - platform: group
    name: eetkamer
    entities:
      - light.hue_color_pendant_down_1
      - light.hue_color_pendant_up_1
  - platform: group
    name: zolder_en_trap
    entities:
      - light.overloop
      - light.trap_hal
      - light.reserve
  - platform: group
    name: slaapkamer
    entities:
      - light.sk_ceiling
      - light.sk_duo_spot_1
      - light.sk_duo_spot_2
  - platform: group
    name: color
    entities:
      - light.hue_lightstrip_plus_1
      - light.staande_lamp
      - light.hue_color_pendant_down_1
      - light.hue_color_pendant_up_1
      - light.computer
      - light.hal
      - light.reserve
      - light.sk_ceiling
  - platform: group
    name: whites
    entities:
      - light.sk_duo_spot_1
      - light.sk_duo_spot_2
      - light.overloop
      - light.keuken_1
      - light.keuken_2
      - light.keuken_3
      - light.trap_hal
  - platform: group
    name: lampen
    entities:
      - light.hue_lightstrip_plus_1
      - light.staande_lamp
      - light.hue_color_pendant_down_1
      - light.hue_color_pendant_up_1
      - light.computer
      - light.hal
      - light.reserve
      - light.sk_ceiling
      - light.sk_duo_spot_1
      - light.sk_duo_spot_2
      - light.overloop
      - light.keuken_1
      - light.keuken_2
      - light.keuken_3
      - light.trap_hal
group:
  switch-wk:
    entities: switch.media_la_switch, switch.media_ra_switch, switch.media_v_switch
  motion_sensors:
    entities: binary_sensor.0x00158d0002b5d42f_occupancy, binary_sensor.0x00158d0002b7eda4_occupancy, binary_sensor.0x00158d0002b8586b_occupancy

input_number:
  lightlevel:
    name: light level for motion sensors
    min: 0
    max: 200
    step: 5
    unit_of_measurement: lx

#binary_sensor:
# custom hue component
#  - platform: huesensor
#remote:
#custom hue component
#  - platform: hueremote
#light:
#  - platform: rflink
#    automatic_add: true
script:
  flash_lights:
    sequence:
      - variables:
          light_entities: "{{states.light|rejectattr('state', 'eq', 'off')|selectattr('attributes.entity_id', 'undefined')|map(attribute='entity_id')|list}} "
      - choose:
          - conditions:
              - "{{ light_entities == '' }}"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: light.hue_lightstrip_plus_1, light.hal
              - variables:
                  light_hal: "{{state_attr('light.hal', 'brightness')|int}}"
                  light_lightstrip: "{{state_attr('light.hue_lightstrip_plus_1', 'brightness')|int}}"
              - service: light.turn_on
                data:
                  entity_id: light.hue_lightstrip_plus_1, light.hal
                  brightness: 100
              - service: light.turn_on
                data:
                  entity_id: light.hue_lightstrip_plus_1, light.hal
                  flash: long
              - delay: 5
              - service: light.turn_on
                data:
                  entity_id: light.hue_lightstrip_plus_1
                  brightness: "{{light_lightstrip}}"
              - service: light.turn_on
                data:
                  entity_id: light.hal
                  brightness: "{{light_hal}}"
              - service: light.turn_off
                data:
                  entity_id: light.hue_lightstrip_plus_1, light.hal
        default:
          - service: light.turn_on
            data:
              entity_id: "{{light_entities}}"
              flash: long

  update_lights_brightness:
    fields:
      brightness_pct:
        description: "brightness in %"
        example: "75"
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: "{{states.light|rejectattr('state', 'eq', 'off')|selectattr('attributes.entity_id', 'undefined')|map(attribute='entity_id')|list}} "
          brightness_pct: >
            {% if brightness_pct %}
              {{brightness_pct}}
            {% else %}
              100
            {% endif %}
          transition: 60
automation:
  - alias: "lights off when leaving"
    id: "782368093283658209"
    trigger:
      - platform: state
        entity_id: input_select.arnoud_status
        to: "Net Weg"
    action:
      - service: homeassistant.turn_off
        entity_id: light.lampen, switch.tplink_b0_4e_26_6b_a1_f5

  - alias: "sunrise lights off"
    id: "47893265301237"
    trigger:
      platform: sun
      event: sunrise
      offset: "00:20:00"
    condition:
      - condition: state
        entity_id: input_boolean.cleaningmode
        state: "off"
    action:
      - service: light.turn_off
        entity_id: light.lampen

  - alias: "lights off weekdays"
    id: "1528912303194"
    trigger:
      - platform: template
        value_template: >
          {% if states('sensor.wakeuplight_time') == None %}
            False
          {% else %}
            {{(as_timestamp(strptime(states('sensor.wakeuplight_time'), '%m/%d/%y %H:%M')) - (6*3600+900))| timestamp_custom('%D %H:%M') == now().strftime('%D %H:%M')}}
          {% endif %}
    action:
      - service: light.turn_off
        data:
          transition: 900
          entity_id: light.lampen

  - alias: "lights off weekenddays"
    id: "1528912303472"
    trigger:
      - at: "23:59:59"
        platform: time
    condition:
      condition: state
      entity_id: "binary_sensor.workday1d"
      state: "off"
    action:
      - service: light.turn_off
        data:
          transition: 900
          entity_id: light.lampen

  - alias: "dim lights in day"
    id: "54618293609860132486029"
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: "overdag"
    condition:
      condition: state
      entity_id: light.lampen
      state: "on"
    action:
      - service: script.update_lights_brightness
        data:
          brightness_pct: 75

  - alias: "dim lights in avond"
    id: "235689056329850982360158"
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: "avond"
    condition:
      condition: state
      entity_id: light.lampen
      state: "on"
    action:
      - service: script.update_lights_brightness
        data:
          brightness_pct: 50

  - alias: "dim lights in nacht"
    id: "56132890612345689532108"
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: "nacht"
    condition:
      condition: state
      entity_id: light.lampen
      state: "on"
    action:
      - service: script.update_lights_brightness
        data:
          brightness_pct: 1
