#cast:
#  media_player:
#  - host: 192.168.3.198
#  - host: 192.168.1.194
#  - host: 192.168.1.132
#  - host: 192.168.1.239
#media_player:
#  - platform: samsungtv
#    host: 192.168.3.222
#    mac: 90:F1:AA:2A:59:50
#  - platform: songpal
#    name: soundbar
#    endpoint: http://192.168.3.152:10000/sony



automation:
  - alias: "Turn off mediacenter when leaving"
    id: "1528971801050"
    trigger:
      - platform: state
        entity_id: input_select.arnoud_status
        to: "Weg"
    action:
      - service: homeassistant.turn_off
        target:
          entity_id: switch.media_group
  - alias: "Turn on mediacenter"
    id: "543216798041047810"
    trigger:
      - platform: time
        at: "16:00:00"
      - platform: state
        entity_id: input_select.arnoud_status
        to: "Net Thuis"
    condition:
      condition: and
      conditions:
        - condition: time
          after: "16:00:00"
          before: "23:59:59"
        - condition: or
          conditions:
            - condition: state
              entity_id: input_select.arnoud_status
              state: "Net Thuis"
            - condition: state
              entity_id: input_select.arnoud_status
              state: "Thuis"
    action:
      - service: homeassistant.turn_on
        target:
          entity_id: switch.media_group
  - alias: "mute players when phone ringing"
    id: "5b49457c-4e6e-4737-846a-9acdf7e5737c"
    trigger:
      - platform: state
        entity_id: sensor.kb2003_telefoon_status
        to: ringing
      - platform: state
        entity_id: sensor.kb2003_telefoon_status
        to: offhook
    condition:
      - "{{is_state('person.arnoud', 'home')}}"
      - "{{(states.media_player|selectattr('state', 'eq', 'playing')|map(attribute='entity_id')|list |length)>0}}"
    action:
      - service: media_player.volume_mute
        target:
          entity_id: "{{states.media_player|selectattr('state', 'eq', 'playing')|map(attribute='entity_id')|list}}"
        data:
          is_volume_muted: true
      - wait_for_trigger:
        - platform: state
          entity_id: sensor.kb2003_telefoon_status
          to: idle
        timeout:
          seconds: 300
      - service: media_player.volume_mute
        target:
          entity_id: "{{states.media_player|selectattr('state', 'eq', 'playing')|map(attribute='entity_id')|list}}"
        data:
          is_volume_muted: false

  - alias: "stop players when leaving"
    id: "8dabd93a-0a59-47a9-a686-7c97c8afa9c4"
    trigger:
      - platform: numeric_state
        entity_id: zone.home
        below: 1
        for: "00:05:00"
    condition:
      - "{{(states.media_player|selectattr('state', 'eq', 'playing')|map(attribute='entity_id')|list |length)>0}}"
      - alias: "no guests in the house"
        condition: state
        entity_id: input_boolean.guests_boolean
        state: "off"
    action:
      - service: media_player.media_stop
        data: {}
        target:
          entity_id: "{{states.media_player|selectattr('state', 'eq', 'playing')|map(attribute='entity_id')|list}}"



#
#sensor:
#  - platform: plex
#    host: 192.168.1.3
#    username: !secret plex_username
#    password: !secret plex_password
#    verify_ssl: false
#
script:
  start_media:
    alias: "Start media"
    fields:
      media_content_id:
        description: "Media content id"
        example: "https://foto-album.duckdns.org/local/audio/Door-bell-sound-ding-dong.mp3"
      media_content_type:
        description: "The type of the content to play. Must be one of image, music, tvshow, video, episode, channel or playlist	"
      entity_id:
        description: "Name(s) of entities to seek media on"
        example: "media_player.living_room_chromecast"
    sequence:
      - service: media_player.volume_mute
        target:
          entity_id: "{{entity_id}}"
        data:
          is_volume_muted: true
      - service: media_player.play_media
        target:
          entity_id: "{{entity_id}}"
        data:
          media_content_id: "https://foto-album.duckdns.org/local/audio/silence_64kb.mp3"
          media_content_type: "music"
      - service: media_player.volume_mute
        target:
          entity_id: "{{entity_id}}"
        data:
          is_volume_muted: false
      - service: media_player.play_media
        target:
          entity_id: "{{entity_id}}"
        data:
          media_content_id: "{{media_content_id}}"
          media_content_type: "{{media_content_type}}"
