#cast:
#  media_player:
#  - host: 192.168.3.198
#  - host: 192.168.1.194
#  - host: 192.168.1.132
#  - host: 192.168.1.239
media_player:
  - platform: samsungtv
    host: 192.168.3.222
    mac: 90:F1:AA:2A:59:50
  - platform: songpal
    name: soundbar
    endpoint: http://192.168.3.152:10000/sony

input_select:
  cast_devices:
    name: select cast device
    options:
      - none


automation:
  - alias: 'Turn off mediacenter when leaving'
    id: '1528971801050'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_select.arnoud_status
        to: 'Weg'
    action:
      - service: homeassistant.turn_off
        entity_id: light.media_group
  - alias: 'Turn on mediacenter'
    id: '543216798041047810'
    hide_entity: true
    trigger:
      - platform: time
        at: '16:00:00' 
      - platform: state
        entity_id: input_select.arnoud_status
        to: 'Net Thuis'
    condition:
     condition: and
     conditions:
      - condition: time
        after: '16:00:00'
        before: '23:59:59'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.arnoud_status
            state: 'Net Thuis'
          - condition: state
            entity_id: input_select.arnoud_status
            state: 'Thuis'
    action:
      - service: homeassistant.turn_on
        entity_id: light.media_group

  - alias: 'set input select cast devices based on sensor chromecast devices'
    id: '87582340659086321048961824360'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: sensor.chromecast_devices
    action:
      - service: input_select.set_options
        data_template:
          entity_id: input_select.cast_devices
          options: >-
            {%- set devices = state_attr('sensor.chromecast_devices', 'devices')  %}
            {%- set ns= namespace(list = []) %}
            {%- for device in devices %}
              {%- set ns.list = ns.list + [device.name] %}
            {%- endfor %}
            {{- ns.list}}
            
#sensor:
#  - platform: plex
#    host: 192.168.1.3
#    username: !secret plex_username
#    password: !secret plex_password
#    verify_ssl: false
#
