binary_sensor:
  - platform: ping
    host: 8.8.8.8
    name: "google"
    count: 3
    scan_interval: 15
template:
  - sensor:
    - name: "google_rtt"
      unique_id: "a2640ba7-762c-4eb0-9932-2c9e61879128"
      state: "{{state_attr('binary_sensor.google', 'round_trip_time_avg')|float}}"
