binary_sensor:
  - platform: ping
    host: 8.8.8.8
    name: "google"
    count: 3
    scan_interval: 15
template:
  - sensor:
    - name: "google_rtt"
      unique_id: "a2640ba7-762c-4eb0-9932-2c9e61879128"
      state: "{{state_attr('binary_sensor.google', 'round_trip_time_avg')|float}}"
    - name: "edgeos_interface_eth0_in_kbps"
      unique_id: "a4852ab9-1bb0-4555-bcb3-d818d687b6da"
      state: "{{state_attr('binary_sensor.edgeos_interface_eth0','KBytes/ps (Received)')|float}}"
    - name: "edgeos_interface_eth0_out_kbps"
      unique_id: "52f85b30-a164-4549-89b4-059e3feee3c7"
      state: "{{state_attr('binary_sensor.edgeos_interface_eth0','KBytes/ps (Sent)')|float}}"
    - name: "edgeos_external_addresses"
      unique_id: "a754689c-8c89-4958-890a-13b5e78dc24e"
      state: "{{state_attr('binary_sensor.edgeos_interface_eth0','addresses')}}"
    - name: "edgeos_device_docker_in_kbps"
      unique_id: "791bc6e4-9801-4ef1-89a2-80f27d6f7495"
      state: "{{state_attr('binary_sensor.edgeos_device_docker','KBytes/ps (Received)')|float}}"
    - name: "edgeos_device_docker_out_kbps"
      unique_id: "e6863e7a-db68-4e9e-9ad6-0354f2a9ba8a"
      state: "{{state_attr('binary_sensor.edgeos_device_docker','KBytes/ps (Sent)')|float}}"
    - name: "edgeos_device_hassio_in_kbps"
      unique_id: "33b3fe8f-abeb-41de-a55e-5d351194a09d"
      state: "{{state_attr('binary_sensor.edgeos_device_hassio','KBytes/ps (Received)')|float}}"
    - name: "edgeos_device_hassio_out_kbps"
      unique_id: "1b9f32a8-4af6-4bc8-a3a8-3a0c6c99684c"
      state: "{{state_attr('binary_sensor.edgeos_device_hassio','KBytes/ps (Sent)')|float}}"
    - name: "edgeos_device_hassbian_in_kbps"
      unique_id: "6587a8ac-9576-4e08-8415-a51cb9dce33a"
      state: "{{state_attr('binary_sensor.edgeos_device_hassbian','KBytes/ps (Received)')|float}}"
    - name: "edgeos_device_hassbian_out_kbps"
      unique_id: "b1ae07ca-aa0d-495e-8d6b-3305f65c9a3a"
      state: "{{state_attr('binary_sensor.edgeos_device_hassbian','KBytes/ps (Sent)')|float}}"
    - name: "edgeos_device_synology415play_in_kbps"
      unique_id: "6d424020-b30c-45a3-a3cb-4e2b9d124919"
      state: "{{state_attr('binary_sensor.edgeos_device_synology415play','KBytes/ps (Received)')|float}}"
    - name: "edgeos_device_synology415play_out_kbps"
      unique_id: "156dd813-6c39-4a1d-8918-8cb944715d42"
      state: "{{state_attr('binary_sensor.edgeos_device_synology415play','KBytes/ps (Sent)')|float}}"
    - name: "ha_uptodate"
      unique_id: "474172c5-042f-42f6-b1b8-d020409b5e91"
      state: >
        {{state_attr('sensor.supervisor_updates','newest_version') == state_attr('sensor.supervisor_updates','current_version')}}
      icon: >
        {{ 'mdi:circle-outline' if state_attr('sensor.supervisor_updates','newest_version') !=
            state_attr('sensor.supervisor_updates','current_version') else 'mdi:check-circle-outline' }}
      unit_of_measurement: Up to date
sensor:
  - platform: command_line
    name: Supervisor updates
    command: 'curl http://supervisor/supervisor/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version,"addons":[.data.addons[] | select(.version != .installed)]}'''
    value_template: ""
    json_attributes:
      - newest_version
      - current_version
      - addons
