binary_sensor:
  - platform: ping
    host: 8.8.8.8
    name: "google"
    count: 3
    scan_interval: 15
template:
  - sensor:
    - name: "google_rtt"
      unique_id: "a2640ba7-762c-4eb0-9932-2c9e61879128"
      state: "{{state_attr('binary_sensor.google', 'round_trip_time_avg')|float}}"
    - name: "esxi_cpu_mhz_used"
      unique_id: "f4068b2f-9c94-4a2f-9186-129e274b4c32"
      state: "{{state_attr('sensor.esxi_vmhost_localhost_local_foto_album_com', 'cpuusage_ghz')|float }}"
      unit_of_measurement: "ghz"
    - name: "esxi_mem_mb_used"
      unique_id: "a985bff2-d76f-4e9c-81a2-2fbe01e82ec4"
      state: "{{state_attr('sensor.esxi_vmhost_localhost_local_foto_album_com', 'memusage_gb')|float}}"
      unit_of_measurement: "GB"
    - name: "esxi_disk_used"
      unique_id: "cc833e94-1fa0-43b0-b81e-cba39a97b700"
      state: "{{(state_attr('sensor.esxi_datastore_main', 'total_space_gb') - state_attr('sensor.esxi_datastore_main', 'free_space_gb'))|int }}"
      unit_of_measurement: "GB"
    - name: "edgeos_interface_eth0_internet_ipv4"
      unique_id: "0f88dc05-1ca4-4293-997b-8ee805b16eb2"
      state: >
        {% if is_state_attr('binary_sensor.router_interface_eth0_status','addresses',['dhcp']) %}
        DHCP
        {% else %}
        {{(state_attr('binary_sensor.router_interface_eth0_status','addresses')|regex_findall(find="'([0-9\.\/]+)', '([0-9:\/a-f]+)'", ignorecase=False))[0][0]}}
        {% endif %}
    - name: "edgeos_interface_eth0_internet_ipv6"
      unique_id: "dadec2ee-eafa-4de0-a0db-a3d67afa602a"
      state: >
        {% if is_state_attr('binary_sensor.router_interface_eth0_status','addresses',['dhcp']) %}
        DHCP
        {% else %}
        {{(state_attr('binary_sensor.router_interface_eth0_status','addresses')|regex_findall(find="'([0-9\.\/]+)', '([0-9:\/a-f]+)'", ignorecase=False))[0][1]}}
        {% endif %}
automation:
  - alias: "ipv4_changed"
    id: "548892fc-7da0-43d1-9e71-8465dd803fbf"
    trigger:
      - platform: state
        entity_id: sensor.edgeos_interface_eth0_internet_ipv4
    condition:
      - and:
          - "{{trigger.from_state.state != 'unavailable'}}"
          - "{{trigger.to_state.state != 'unavailable'}}"
          - "{{trigger.from_state.state != 'DHCP'}}"
          - "{{trigger.to_state.state != 'DHCP'}}"
    action:
      - service: notify.persistent_notification
        data:
          title: "IPv4 address changed"
          message: "Internet address changed from {{trigger.from_state.state}} to {{trigger.to_state.state}}"
  - alias: "reload-edgeos"
    id: "a2c7f335-8592-4a50-8b64-148a8abf20c6"
    trigger:
      - platform: time
        at: "00:30:00"
    action:
      - service: homeassistant.reload_config_entry
        data: {}
        target:
          device_id: a22c03e9fff39036212524820e2f68b5

sensor:
  - platform: snmp
    name: "esxi cpu 1"
    baseoid: 1.3.6.1.2.1.25.3.3.1.2.1
    unique_id: "75e6a7bc-5c28-4f00-af0b-f4509327aedb"
    host: 192.168.3.4
    auth_key: !secret esxi_snmp_key
    auth_protocol: hmac-sha
    priv_key: !secret esxi_snmp_key
    priv_protocol: aes-cfb-128
    username: !secret esxi_snmp_user
    version: "3"
    unit_of_measurement: "%"
    accept_errors: true
    default_value: 0
    icon: "mdi:cpu-64-bit"
    
  - platform: snmp
    name: "esxi cpu 2"
    baseoid: 1.3.6.1.2.1.25.3.3.1.2.2
    unique_id: "cc95cbe4-af1b-47e4-ad4c-23eb6a54d652"
    host: 192.168.3.4
    auth_key: !secret esxi_snmp_key
    auth_protocol: hmac-sha
    priv_key: !secret esxi_snmp_key
    priv_protocol: aes-cfb-128
    username: !secret esxi_snmp_user
    version: "3"
    unit_of_measurement: "%"
    accept_errors: true
    default_value: 0
    icon: "mdi:cpu-64-bit"

  - platform: snmp
    name: "esxi cpu 3"
    baseoid: 1.3.6.1.2.1.25.3.3.1.2.3
    unique_id: "56469141-371d-4ac0-b70a-950f7dcaa05c"
    host: 192.168.3.4
    auth_key: !secret esxi_snmp_key
    auth_protocol: hmac-sha
    priv_key: !secret esxi_snmp_key
    priv_protocol: aes-cfb-128
    username: !secret esxi_snmp_user
    version: "3"
    unit_of_measurement: "%"
    accept_errors: true
    default_value: 0
    icon: "mdi:cpu-64-bit"

  - platform: snmp
    name: "esxi cpu 4"
    baseoid: 1.3.6.1.2.1.25.3.3.1.2.4
    unique_id: "ce70b7bd-d7a5-4b3a-bad0-8b3c4dd5ee0d"
    host: 192.168.3.4
    auth_key: !secret esxi_snmp_key
    auth_protocol: hmac-sha
    priv_key: !secret esxi_snmp_key
    priv_protocol: aes-cfb-128
    username: !secret esxi_snmp_user
    version: "3"
    unit_of_measurement: "%"
    accept_errors: true
    default_value: 0
    icon: "mdi:cpu-64-bit"

  - platform: snmp
    name: "edgeos cpu 1"
    baseoid: 1.3.6.1.2.1.25.3.3.1.2.196608
    unique_id: "d3f4cee1-fc9a-48b6-b038-5cdd48f3eb6d"
    host: 192.168.3.1
    auth_key: !secret edgeos_snmp_key
    auth_protocol: hmac-sha
    priv_key: !secret edgeos_snmp_key
    priv_protocol: aes-cfb-128
    username: !secret edgeos_snmp_user
    version: "3"
    unit_of_measurement: "%"
    accept_errors: true
    default_value: 0
    icon: "mdi:cpu-64-bit"

  - platform: snmp
    name: "edgeos cpu 2"
    baseoid: 1.3.6.1.2.1.25.3.3.1.2.196609
    unique_id: ""
    host: 192.168.3.1
    auth_key: !secret edgeos_snmp_key
    auth_protocol: hmac-sha
    priv_key: !secret edgeos_snmp_key
    priv_protocol: aes-cfb-128
    username: !secret edgeos_snmp_user
    version: "3"
    unit_of_measurement: "%"
    accept_errors: true
    default_value: 0
    icon: "mdi:cpu-64-bit"

  - platform: snmp
    name: "edgeos cpu 3"
    baseoid: 1.3.6.1.2.1.25.3.3.1.2.196610
    unique_id: "524f06c2-75df-48f0-85f2-1ebf496f94dc"
    host: 192.168.3.1
    auth_key: !secret edgeos_snmp_key
    auth_protocol: hmac-sha
    priv_key: !secret edgeos_snmp_key
    priv_protocol: aes-cfb-128
    username: !secret edgeos_snmp_user
    version: "3"
    unit_of_measurement: "%"
    accept_errors: true
    default_value: 0
    icon: "mdi:cpu-64-bit"

  - platform: snmp
    name: "edgeos cpu 4"
    baseoid: 1.3.6.1.2.1.25.3.3.1.2.196611
    unique_id: "bae11c03-95f0-46c8-be38-91b3de540ffb"
    host: 192.168.3.1
    auth_key: !secret edgeos_snmp_key
    auth_protocol: hmac-sha
    priv_key: !secret edgeos_snmp_key
    priv_protocol: aes-cfb-128
    username: !secret edgeos_snmp_user
    version: "3"
    unit_of_measurement: "%"
    accept_errors: true
    default_value: 0
    icon: "mdi:cpu-64-bit"