sensor:
  - platform: p2000
    name: Brandweer
    regios: 10
    disciplines: 1
    radius: 7500
  - platform: p2000
    name: Ambulance
    regios: 10
    disciplines: 2
    radius: 1000
  - platform: p2000
    name: Trauma-heli
    regios: 8,13,17
    disciplines: 2
    radius: 15000
    capcodes: 120901,923993,1420059
  - platform: p2000
    name: grip
    regios: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24
    radius: 30000
    contains: "GRIP"
