input_select:
  arnoud_status:
    name: Arnoud
    options:
      - Thuis
      - Net Thuis
      - Net Weg
      - Weg
  helen_status_dropdown:
    name: placeholder
    options:
      - Thuis
      - Net Thuis
      - Net Weg
      - Weg
  house_mode:
    name: House
    options:
      - weg
      - overdag
      - avond
      - nacht
input_boolean:
  guests_boolean:
    name: Guests in the house

#device_tracker:
#  - platform: gpslogger
#  - platform: bluetooth_tracker
#    new_device_defaults:
#      track_new_devices: false
#  - platform: tplink_router
#    host: 192.168.3.1
#    username: !secret tplink_user
#    password: !secret tplink_password

sensor:
  - platform: template
    sensors:
      arnoud_status:
        value_template: '{{ states("input_select.arnoud_status") }}'
        friendly_name: "Arnoud"
      prox_home_dir_of_travel:
        value_template: '{{state_attr("proximity.home","dir_of_travel")}}'
        friendly_name: "Direction of travel to/from home"

binary_sensor:
  - platform: workday
    country: NL
  - platform: workday
    name: workday1d
    country: NL
    days_offset: 1

proximity:
  home:
    ignored_zones:
      - Ymke
    devices:
      #      - device_tracker.4dd0404d
      #      - device_tracker.unknown
      - device_tracker.kb2003
      - device_tracker.467cfa38bbada1bf
      - device_tracker.sz_436_p_device_tracker
    unit_of_measurement: km
    tolerance: 50

automation:
  - alias: 'edwin-binnen'
    id: c97ea8e3-8a93-4a66-ad8e-54e59c44b01f 
    trigger:
      - platform: state
        entity_id: device_tracker.edgeos_oneplus_nord2_5g_edwin
        to: 'home'
    action:
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.ha_alarm
          code: !secret alarm_code
      - service: input_boolean.turn_on
        entity_id: input_boolean.guests_boolean
      - wait_for_trigger:
          platform: state
          entity_id: device_tracker.edgeos_oneplus_nord2_5g_edwin
          to: 'away'
          for: '00:15:00'
        timeout: "10:00:00"
      - service: input_boolean.turn_off
        entity_id: input_boolean.guests_boolean

  - alias: "Mark person as just arrived"
    id: "548327489170419324086"
    trigger:
      - platform: state
        entity_id: person.arnoud
        to: "home"
    action:
      - service: input_select.select_option
        data:
          entity_id: >
            {% if trigger.entity_id == 'person.arnoud' %}
              input_select.arnoud_status
            {% else %}
              input_select.helen_status_dropdown
            {% endif %}
          option: >
            {% if trigger.entity_id == 'person.arnoud' %}
              {% if states('input_select.arnoud_status') == 'Net Weg' %}
                Thuis
              {% else %}
                Net Thuis
              {% endif %}
            {% else %}
              {% if states('input_select.helen_status_dropdown') == 'Net Weg' %}
                Thuis
              {% else %}
                Net Thuis
              {% endif %}
            {% endif %}
  - alias: "Mark person as home"
    id: "014567856438345707843571"
    trigger:
      - platform: state
        entity_id: input_select.arnoud_status
        to: "Net Thuis"
        for:
          minutes: 15
      - platform: state
        entity_id: input_select.arnoud_status
        from: "Net Weg"
        to: "Net Thuis"
    action:
      - service: input_select.select_option
        data:
          entity_id: >
            {% if trigger.entity_id == 'input_select.arnoud_status' %}
              input_select.arnoud_status
            {% else %}
              input_select.helen_status_dropdown
            {% endif %}
          option: Thuis
  - alias: "Mark person as just left"
    id: "578344801378074356"
    trigger:
      - platform: state
        entity_id: person.arnoud
        from: "home"
    action:
      - service: input_select.select_option
        data:
          entity_id: >
            {% if trigger.entity_id == 'person.arnoud' %}
              input_select.arnoud_status
            {% else %}
              input_select.helen_status_dropdown
            {% endif %}
          option: Net Weg
  - alias: "Mark person as away"
    id: "80941237089760310"
    trigger:
      - platform: state
        entity_id: input_select.arnoud_status
        to: "Net Weg"
        for:
          minutes: 15
    action:
      - service: input_select.select_option
        data:
          entity_id: >
            {% if trigger.entity_id == 'input_select.arnoud_status' %}
              input_select.arnoud_status
            {% else %}
              input_select.helen_status_dropdown
            {% endif %}
          option: Weg

  - alias: "change house status"
    id: "3a35f68a-b0c5-416e-8761-c85d2e62a63b"
    trigger:
      - platform: time
        at:
          - "00:00:01"
          - input_datetime.bedtime
          - input_datetime.wakeuptime
      - platform: state
        entity_id: input_select.arnoud_status
        for: "00:05:00"
      - platform: state
        entity_id: input_boolean.guests_boolean
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 3.5
        id: "sun_below"
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: 3.5
        id: "sun_above"
    action:
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: input_select.arnoud_status
                    state: "Thuis"
                  - condition: state
                    entity_id: input_select.arnoud_status
                    state: "Net Thuis"
                  - condition: state
                    entity_id: input_boolean.guests_boolean
                    state: "on"
            sequence:
              #              - service: notify.pushover
              #                data:
              #                  title: house-status
              #                  message: "house-status at home trigger: {{trigger}}"
              - choose:
                  - conditions:
                      - condition: or
                        conditions:
                          - condition: template
                            value_template: "{{ trigger.entity_id == 'input_datetime.bedtime' }}"
                    sequence:
                      #                      - service: notify.pushover
                      #                        data:
                      #                          title: house-status
                      #                          message: "1 status set to nacht by {{trigger.platform}}"
                      - service: input_select.select_option
                        data:
                          entity_id: input_select.house_mode
                          option: nacht
                  - conditions:
                      - condition: or
                        conditions:
                          - condition: trigger
                            id: "sun_below"
                          - condition: sun
                            after: sunset
                    sequence:
                      #                      - service: notify.pushover
                      #                        data:
                      #                          title: house-status
                      #                          message: "2 status set to avond by {{trigger.platform}}"
                      - service: input_select.select_option
                        data:
                          entity_id: input_select.house_mode
                          option: avond
                  - conditions:
                      - condition: template
                        value_template: "{{ trigger.entity_id == 'input_datetime.wakeuptime' }}"
                    sequence:
                      #                      - service: notify.pushover
                      #                        data:
                      #                          title: house-status
                      #                          message: "3 status set to overdag by {{trigger.platform}}"
                      - service: input_select.select_option
                        data:
                          entity_id: input_select.house_mode
                          option: overdag
                  - conditions:
                      - condition: sun
                        before: sunrise
                    sequence:
                      #                      - service: notify.pushover
                      #                        data:
                      #                          title: house-status
                      #                          message: "4 status set to nacht by {{trigger.platform}}"
                      - service: input_select.select_option
                        data:
                          entity_id: input_select.house_mode
                          option: nacht
                  - conditions:
                      - condition: or
                        conditions:
                          - condition: trigger
                            id: "sun_above"
                          - condition: sun
                            after: sunrise
                            before: sunset
                    sequence:
                      #                      - service: notify.pushover
                      #                        data:
                      #                          title: house-status
                      #                          message: "5 status set to overdag by {{trigger.platform}} "
                      - service: input_select.select_option
                        data:
                          entity_id: input_select.house_mode
                          option: overdag
                default:
                  - service: notify.pushover
                    data:
                      title: house-status
                      message: "status not set as no conditions match "
        default:
          #          - service: notify.pushover
          #            data:
          #              title: house-status
          #              message: "7 status set to away {{trigger}}"
          - service: input_select.select_option
            data:
              entity_id: input_select.house_mode
              option: weg
