#ring:
#  username: !secret ring_username
#  password: !secret ring_password
#binary_sensor:
#  - platform: ring
#    monitored_conditions:
#      - ding
#      - motion
# camera:
#   - platform: ring
# ffmpeg:

#sensor:
  #  - platform: ring
  #    monitored_conditions:
  #      - battery
  #      - last_activity
  #      - last_ding
  #      - last_motion
  #      - volume

template:
  - sensor:
      - name: "last_ring"
        unique_id: "4a23d188-2f96-4e30-ada7-8687a5fad980"
        state: >-
          {% if state_attr('sensor.front_door_last_ding','created_at') != None %}
            {{relative_time(state_attr('sensor.front_door_last_ding','created_at'))   }}
          {% endif %}
      - name: "last_motion"
        unique_id: "716f0459-4145-4e87-8245-6ad4657f52e5"
        state: >-
          {% if state_attr('sensor.front_door_last_motion','created_at') != None %}
            {{relative_time(state_attr('sensor.front_door_last_motion','created_at')) }}
          {% endif %}

automation:
  - alias: "flash lights with doorbell"
    id: "753125809170657784308"
    trigger:
      platform: state
      entity_id: binary_sensor.front_door_ding
      to: "on"
    action:
      - service: script.turn_on
        target:
          entity_id: script.flash_lights
      - alias: "Play sound when there is someone at the door"
        service: script.google_home_resume
        data:
          action:
            - service: media_player.volume_set
              target:
                entity_id: media_player.speakers
              data:
                volume_level: "{{states('input_number.tts_volume')| float}}"
            - service: media_player.play_media
              target:
                entity_id: media_player.speakers
              data:
                media_content_type: music
                media_content_id: "https://foto-album.duckdns.org/local/audio/Door-bell-sound-ding-dong.mp3"
                extra:
                  thumb: "https://brands.home-assistant.io/_/homeassistant/logo.png"
                  title: Doorbell
            - delay: "00:00:03"
            - service: tts.google_say
              target:
                entity_id: media_player.speakers
              data:
                message: "Er is iemand aan de deur"
                language: "nl"
            - delay: "00:00:10"