automation:
  - alias: "tablet lader aan"
    id: "54263098623458560"
    trigger:
      platform: numeric_state
      entity_id: sensor.scarlet_battery_level
      below: 40
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.tablet_lader

  - alias: "Tablet lader uit"
    id: "57802395701892350865743010983"
    trigger:
      platform: numeric_state
      entity_id: sensor.scarlet_battery_level
      above: 90
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.tablet_lader
