automation:
  - alias: "test"
    id: "de51b506-99f3-4d4c-bcb5-3abeec41921c9"
    trigger:
      platform: time
      at: 07:00
    
    action:
      - variables:
          weather_entity: sensor.nextday_weather
          zone_entity: zone.home
          prompt: |-
            Please generate text for a notification that will be sent to the users
            smartphone with helpful information.
    
            You are a helpful personal agent that generates text for the user:
            - Your answers are helpful, friendly, warm, insightful.
            - Your answers are not technical, and do not include Home Assistant internal details such as entities in responses.
            - Your messages help the user prepare for their day, for example:
              - Making note of unusual weather for the location and time of year (but not mundane details like "0% chance of precipitation")
              - How much time remaining until their first meeting
              - Anything that may be special or unique, such as celebrating a birthday
      - alias: Fetch Calendar Agenda
        service: calendar.get_events
        target: 
          entity_id:
            - calendar.abuurmangmailcom
            - calendar.action
        response_variable: agenda
        data:
          duration: 
            hours: 18
    
      - alias: "Conversation Agent Notification Text"
        service: conversation.process
        data:
          text: |-
            Time: {{ now() }}
            {%- if zone_entity is defined %}
            Latitude: {{ state_attr(zone_entity, 'latitude') | round(1) }}
            Longitude: {{ state_attr(zone_entity, 'longitude') | round(1) }}
            {% endif %}
    
            {%- if weather_entity is defined %}
            {%- set forecast = state_attr(weather_entity, 'forecast')[0] %}
            {%- set temperature_unit = state_attr(weather_entity, 'temperature_unit') -%}
            Weather: {{ forecast.condition }} ({{ forecast.temperature }}{{ temperature_unit }}, {{ forecast.precipitation }}% precipitation)
            {%- endif %}
            Calendar events for the next {{ calendar_duration.hours }}:
            {%- if not agenda.items() %}
              - No upcoming events.
            {%- else %}
              {%- for key, value in agenda.items() %}
                {% if key == "calendar.action" %}
                  {%- for event in value.events %}
                    {%- if event.summary is defined %}
                      {%- if  event.summary != "Private Appointment" and event.summary != "lunch"  and event.summary != "outside working hours" %}
                        - Summary: {{ event.summary }}
                          Start-End: {% if event.start is defined %}{{ event.start }} to {{ event.end }}{% else %}All Day{% endif %}
                        {%- if event.descripton is defined %}
                          Description: {{ event.descripton }}
                        {% endif -%}
                        {%- if event.location is defined %}
                          Location: {{ event.location }}
                        {% endif -%}
                      {% endif -%}
                    {%- else %}
                      - Start-End: {% if event.start is defined %}{{ event.start }} to {{ event.end }}{% else %}All Day{% endif %}
                      {%- if event.descripton is defined %}
                        Description: {{ event.descripton }}
                      {% endif -%}
                      {%- if event.location is defined %}
                        Location: {{ event.location }}
                      {% endif -%}
                    {% endif -%}
                  {%- endfor %}
                {% else %}
                  {%- if event.summary is defined %}
                    {%- if  event.summary != "Private Appointment" and event.summary != "lunch"  and event.summary != "outside working hours" %}
                      - Summary: {{ event.summary }}
                        Start-End: {% if event.start is defined %}{{ event.start }} to {{ event.end }}{% else %}All Day{% endif %}
                      {%- if event.descripton is defined %}
                        Description: {{ event.descripton }}
                      {% endif -%}
                      {%- if event.location is defined %}
                        Location: {{ event.location }}
                      {% endif -%}
                    {% endif -%}
                  {%- else %}
                    - Start-End: {% if event.start is defined %}{{ event.start }} to {{ event.end }}{% else %}All Day{% endif %}
                    {%- if event.descripton is defined %}
                      Description: {{ event.descripton }}
                    {% endif -%}
                    {%- if event.location is defined %}
                      Location: {{ event.location }}
                    {% endif -%}
                  {% endif -%}
                {%- endif %}
              {%- endfor %}
            {%- endif %}
            {{ prompt }}
          agent_id: 7df39e215dafbd1d3d853b5366ab81c1
        response_variable: agent
      - alias: "Send notification"
        service: notify.webbrowser
        data:
          title: "{{ now().strftime('%A') }} Agenda"
          message: "{{ agent.response.speech.plain.speech }}"
      - alias: mail
        service: notify.a_buurman_gmail_com
        data:
          message: "{{ agent.response.speech.plain.speech }}"
          title: "{{ now().strftime('%A') }} Agenda"
          target:
            - "a.buurman@gmail.com"