automation:
  - alias: "test"
    id: "de51b506-99f3-4d4c-bcb5-3abeec41921c9"
    trigger:
      - trigger: time_pattern
        minutes: /5

    action:
      - alias: Fetch Calendar Agenda
        action: calendar.get_events
        target:
          entity_id:
            - calendar.abuurmangmailcom
            - calendar.action_2
        response_variable: agenda
        data:
          duration:
            hours: 18
      - action: notify.mobile_app_oneplus13
        data:
          message: |
            {% set merged_agenda = (merge_response(agenda) | sort(attribute='start')) %}
            {% set ns = namespace(valid_events=0) %}
            {%- if merged_agenda|length == 0 %}
              - No upcoming events.
            {%- else %}
              {%- for event in merged_agenda %}
                {%- if event.summary is defined %}
                  {%- if  event.summary != "Private Appointment" and event.summary != "lunch"  and event.summary != "outside working hours" %}
                    {% set ns.valid_events = ns.valid_events + 1 %}
                    - Summary: {{ event.summary }}
                      Start-End: {% if event.start is defined %}{{ event.start }} to {{ event.end }}{% else %}All Day{% endif %}
                    {%- if event.descripton is defined %}
                      Description: {{ event.descripton }}
                    {% endif -%}
                    {%- if event.location is defined %}
                      Location: {{ event.location }}
                    {% endif -%}
                  {% endif -%}
                {%- else %}
                  {% set ns.valid_events = ns.valid_events + 1 %}
                  - Start-End: {% if event.start is defined %}{{ event.start }} to {{ event.end }}{% else %}All Day{% endif %}
                  {%- if event.descripton is defined %}
                    Description: {{ event.descripton }}
                  {% endif -%}
                  {%- if event.location is defined %}
                    Location: {{ event.location }}
                  {% endif -%}
                {% endif -%}
                {% if loop.last and ns.valid_events == 0 %}
                  - No upcoming events.
                {% endif %}
              {%- endfor %}
            {%- endif %}
          title: "Test"
          data:
            priority: 1
