toon:
  client_id: !secret toon_consumer_key
  client_secret: !secret toon_consumer_secret
input_select:
  heating:
    name: Heating options
    options:
      - sleep
      - home
      - comfort
      - away
    icon: mdi:fire

input_number:
  thermostat_set_point:
    name: Thermostaat
    min: 5
    max: 35
    initial: 15
    step: 0.5
    unit_of_measurement: °C
    icon: mdi:thermometer

template:
  - sensor:
    - name: "heating_set_temperature"
      unique_id: "1394c112-73e9-4884-b8a3-6c01ce3e5d85"
      state: "{{state_attr('climate.toon_thermostat', 'temperature') | float }}"
      device_class: "temperature"
      unit_of_measurement: "°C"
    - name: "heating_preset_mode"
      unique_id: "0f64357c-5e9d-4939-aa83-180eee53740d"
      state: "{{state_attr('climate.toon_thermostat', 'preset_mode')}}"
    - name: "toon_action"
      unique_id: "f35bbc32-e09b-418b-84cf-970d0378bf91"
      state: "{{state_attr('climate.toon_thermostat', 'hvac_action')}}"
    - name: "thermostat_condition"
      unique_id: "04b4cc23-5941-4fb4-901e-452e0fdb0153"
      state: >
        {% if is_state('sensor.buiten_temperature', 'unknown') %}
          {% if is_state('sensor.woonkamer_temperature', 'unknown') %}
            {{(states('input_number.berkhout_temperatuur_0d') |float ) <20}}
          {% else %}
            {{(states('sensor.buiten_temperature') |float ) <20  and (states('input_number.berkhout_temperatuur_0d') |float ) <20 }}
          {% endif %}
        {% else %}
          {{(( states('sensor.buiten_temperature')  )|float) < (( states('sensor.woonkamer_temperature') ) | float) and (states('sensor.buiten_temperature') |float ) <20  and (states('input_number.berkhout_temperatuur_0d') |float ) <20 }}
        {% endif %}

timer:
  toon_automation:
    name: Time remaining
    duration: 120
automation:
  - alias: "kachel nieuw"
    id: "432578090243508970892435"
    trigger:
      - platform: state
        entity_id: input_select.arnoud_status
        to: "Net Thuis"
      - platform: state
        entity_id: input_select.arnoud_status
        to: "Weg"
        for: "01:00:00"
      - platform: numeric_state
        entity_id: proximity.home
        above: 11.8
        id: "proximity_above"
      - platform: numeric_state
        entity_id: proximity.home
        below: 25
        id: "proximity_below"
      - platform: state
        entity_id: group.windows_kachel
        from: "off"
        to: "on"
        for: "00:05:00"
      - platform: state
        entity_id: person.arnoud
        from: "Action"
        for: "00:03:00"
        id: "leave_action"
      - platform: state
        entity_id: group.windows_kachel
        from: "on"
        to: "off"
      - platform: time
        at:
          - "09:00:00"
          - "23:00:00"
          - "21:30:00"
      - platform: time
        at:
          - input_datetime.pre_heat_time
        id: "pre_heat"
      - platform: state
        entity_id: sensor.thermostat_condition
    action:
      - choose:
          - conditions:
              condition: trigger
              id: "proximity_above"
            sequence:
              - alias: "zet kachel uit"
                service: script.kachel_mode
                data:
                  mode: "away"
          - conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id: "pre_heat"
                  - condition: numeric_state
                    entity_id: sensor.badkamer_temperature
                    below: 20
            sequence:
              - alias: "zet kachel aan"
                service: script.kachel_mode
                data:
                  mode: "comfort"
              - wait_for_trigger:
                  platform: numeric_state
                  entity_id: sensor.badkamer_temperature
                  above: 20
                timeout: "00:30:00"
              - alias: "zet kachel uit"
                service: script.kachel_mode
                data:
                  mode: "away"
          - conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: sensor.thermostat_condition
                    state: "True"
                  - condition: state
                    entity_id: group.windows_kachel
                    state: "off"
                  - condition: or
                    conditions:
                      - condition: and
                        conditions:
                          - condition: time
                            after: "08:59:59"
                            before: "21:00:00"
                          - condition: state
                            entity_id: binary_sensor.workday_sensor
                            state: "on"
                      - condition: and
                        conditions:
                          - condition: time
                            after: "08:59:59"
                            before: "22:00:00"
                          - condition: state
                            entity_id: binary_sensor.workday_sensor
                            state: "off"
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: input_select.arnoud_status
                        state: "Thuis"
                      - condition: state
                        entity_id: input_select.arnoud_status
                        state: "Net Thuis"
                      - condition: trigger
                        id: "proximity_below"
                      - condition: trigger
                        id: "action_leave"
            sequence:
              - alias: "zet kachel aan"
                service: script.kachel_mode
                data:
                  mode: "home"
          - conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: binary_sensor.workday1d
                    state: "on"
                  - condition: time
                    after: "21:29:59"
            sequence:
              - alias: "zet kachel uit"
                service: script.kachel_mode
                data:
                  mode: "away"
        default:
          - alias: "zet kachel uit"
            service: script.kachel_mode
            data:
              mode: "away"

  ########################
  ##
  ## keep state between Toon and inputs
  ##
  ########################

  - alias: "zet heating input select based on toon output"
    id: "32847030987420324"
    trigger:
      platform: state
      entity_id: sensor.heating_preset_mode
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: sensor.heating_preset_mode
          state: sleep
        - condition: state
          entity_id: sensor.heating_preset_mode
          state: home
        - condition: state
          entity_id: sensor.heating_preset_mode
          state: comfort
        - condition: state
          entity_id: sensor.heating_preset_mode
          state: away
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.heating
        data:
          option: "{{states('sensor.heating_preset_mode')}}"
  - alias: "zet toon based on heating input select"
    id: "3098476890309834039342"
    trigger:
      platform: state
      entity_id: input_select.heating
    condition:
      condition: state
      entity_id: timer.toon_automation
      state: idle
    action:
      - service: climate.set_preset_mode
        target:
          entity_id: climate.toon_thermostat
        data:
          preset_mode: "{{states('input_select.heating')}}"
  - alias: "zet toon thermostaat based on input value"
    id: "98487940987349821"
    trigger:
      platform: state
      entity_id: input_number.thermostat_set_point
    condition:
      condition: and
      conditions:
        - "{{ ( states('input_number.thermostat_set_point')  ) != ( states('sensor.heating_set_temperature') ) }}"
        - condition: state
          entity_id: timer.toon_automation
          state: idle
    action:
      - service: climate.set_temperature
        target:
          entity_id: climate.toon_thermostat
        data:
          temperature: "{{states('input_number.thermostat_set_point')}}"
  - alias: "zet thermostaat input value based on toon"
    id: "230983248701908743"
    trigger:
      platform: state
      entity_id: sensor.heating_set_temperature
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.thermostat_set_point
        data:
          value: "{{ states('sensor.heating_set_temperature') }}"
script:
  kachel_mode:
    fields:
      mode:
        description: "Kachel mode"
        example: "away"
    sequence:
      - service: timer.start
        target:
          entity_id: timer.toon_automation
      - repeat:
          sequence:
            - alias: "zet kachel mode"
              service: climate.set_preset_mode
              target:
                entity_id: climate.toon_thermostat
              data:
                preset_mode: "{{ mode }}"
            - delay:
                seconds: 30
          until: "{{ is_state('sensor.heating_preset_mode', mode ) }}"
