automation:
  - alias: "Update Available Notifications"
    id: "43897023907390"
    trigger:
      trigger: state
      entity_id:
        - update.home_assistant_core_update
        - update.home_assistant_operating_system_update
        - update.home_assistant_supervisor_update
    conditions:
      - "{{trigger.from_state.attributes.latest_version}} != {{trigger.to_state.attributes.latest_version}} "
    action:
      action: notify.mobile_app_oneplus13
      data:
        message: >
          Update to {{trigger.to_state.attributes.title}} to {{trigger.to_state.attributes.latest_version}} is available.
          see {{trigger.to_state.attributes.release_url}}
        # IOS url
        url: "{{trigger.to_state.attributes.release_url}}"
        # Android URL
        clickAction: "{{trigger.to_state.attributes.release_url}}"
