input_boolean:
  wakeuplight_automatic:
    name: Wakeup light based on calendar
  wakeuplight_manual:
    name: Wakeup light based on manual input
input_number:
  wul_time_before_leave:
    name: Wakeup light time before leave
    min: 0
    max: 60
    step: 1
    unit_of_measurement: minutes
input_datetime:
  wul_manual_time:
    name: Wakeup light manual time
    has_date: false
    has_time: true

script:
  wakeup_light:
    sequence:
      - alias: "turn off brightness automation"
        service: automation.turn_off
        target:
          entity_id: automation.update_brightness_based_on_house_status
      - service: light.turn_on
        target:
          entity_id: light.sk_ceiling
        data:
          brightness: 1
          xy_color:
            - 0.64
            - 0.33
      - service: light.turn_on
        target:
          entity_id: light.sk_ceiling
        data:
          transition: 600
          brightness_pct: 100
          xy_color:
            - 0.442
            - 0.447
      - delay:
          seconds: 5
      - alias: "turn on brightness automation"
        service: automation.turn_on
        target:
          entity_id: automation.update_brightness_based_on_house_status
      - alias: volume
        service: media_player.volume_set
        target:
          entity_id: media_player.slaapkamer_speaker
        data:
          volume_level: "0"
      - alias: fix playing
        repeat:
          while:
            - condition: not
              conditions:
                - condition: state
                  entity_id: media_player.slaapkamer_speaker
                  state: "playing"
          sequence:
            - alias: mediaplayer_setmedia
              service: media_player.play_media
              target:
                entity_id: media_player.slaapkamer_speaker
              data:
                media_content_id: "https://streaming.radio.co/s5c5da6a36/listen"
                media_content_type: audio/mp4
            - alias: mediaplayer_play
              service: media_player.media_play
              target:
                entity_id: media_player.slaapkamer_speaker
            - delay:
                seconds: 5
      - alias: repeat
        repeat:
          sequence:
            - service: media_player.volume_set
              target:
                entity_id: media_player.slaapkamer_speaker
              data:
                volume_level: "{{state_attr('media_player.slaapkamer_speaker', 'volume_level')|float +0.05}}"
            - delay:
                seconds: 30
          until: "{{(state_attr('media_player.slaapkamer_speaker', 'volume_level')|float) > 0.95 }}"

      - delay:
          minutes: 1
      - alias: opstaan!
        service: tts.google_say
        target:
          entity_id: media_player.slaapkamer_speaker
        data:
          message: "Goeie morgen, tijd om op te staan"
          language: "nl"
      - delay:
          minutes: 1
      - alias: volume
        service: media_player.volume_set
        target:
          entity_id: media_player.slaapkamer_speaker
        data:
          volume_level: "0.4"
automation:
  - alias: "wakeup light"
    id: "342090870414607831"
    trigger:
      - platform: time
        at:
          - input_datetime.wakeuplight_time
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.wakeuplight_automatic
          state: "on"
        - condition: or
          conditions:
            - condition: state
              entity_id: sensor.prox_home_dir_of_travel
              state: "arrived"
            - condition: state
              entity_id: sensor.prox_home_dir_of_travel
              state: "towards"
    action:
      service: script.wakeup_light

  - alias: "Manual wakeup light"
    id: "6583925910238569382012"
    trigger:
      - platform: time
        at: input_datetime.wul_manual_time
    condition:
      condition: state
      entity_id: input_boolean.wakeuplight_manual
      state: "on"
    action:
      - alias: "run script wakeuplight"
        service: script.wakeup_light
      - alias: "turn manual wakeup off"
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.wakeuplight_manual
