#camera:
  #  - platform: generic
  #    name: buienradar
  #    still_image_url:  https://api.buienradar.nl/image/1.0/RadarMapNL?w=500&h=512
  #  - platform: generic
  #    still_image_url:  http://cdn.knmi.nl/knmi/map/page/weer/actueel-weer/neerslagradar/WWWRADAR_loop.gif
#  - platform: buienradar
#    name: buienradar
input_number:
  berkhout_temperatuur_0d:
    name: Berkhout temparatuur forcast vandaag
    unit_of_measurement: °C
    min: -50
    max: 50
    mode: box
    icon: mdi:thermometer

#weather:
#  - platform: buienradar
#    name: "Berkhout"
#    latitude: 52.65
#    longitude: 4.98
sensor:
#  - platform: buienradar
#    name: "Berkhout"
#    latitude: 52.65
#    longitude: 4.98
#    timeframe: 30
#    monitored_conditions:
#      - symbol
#      - humidity
#      - temperature
#      - windspeed
#      - conditiondetailed
#      - condition
#      - conditioncode
#      - visibility
#      - irradiance
#      - windazimuth
#      - precipitation_forecast_total
#      - temperature_1d
#  - platform: buienradar
#    name: "de Bilt"
#    latitude: 52.10
#    longitude: 5.18
#    monitored_conditions:
#      - symbol
#  - platform: buienradar
#    name: "Schiphol"
#    latitude: 52.30
#    longitude: 4.77
#    monitored_conditions:
#      - symbol
#      - pressure
  - platform: statistics
    entity_id: sensor.buiten_temperature
    max_age:
      hours: 24
    sampling_size: 500
    precision: 1
    name: buiten_temperature_stats
  - platform: statistics
    entity_id: sensor.zolder_voor_temperature
    max_age:
      hours: 24
    sampling_size: 500
    precision: 1
    name: zolder_voor_temperature_stats
  - platform: statistics
    entity_id: sensor.zolder_achter_temperature
    max_age:
      hours: 24
    sampling_size: 500
    precision: 1
    name: zolder_achter_temperature_stats
  - platform: statistics
    entity_id: sensor.studeerkamer_temperature
    max_age:
      hours: 24
    sampling_size: 500
    precision: 1
    name: studeerkamer_temperature_stats
  - platform: statistics
    entity_id: sensor.buiten_temperature
    max_age:
      hours: 24
    sampling_size: 500
    precision: 1
    name: slaapkamer_temperature_stats
  - platform: statistics
    entity_id: sensor.badkamer_temperature
    max_age:
      hours: 24
    sampling_size: 500
    precision: 1
    name: badkamer_temperature_stats
  - platform: statistics
    entity_id: sensor.woonkamer_temperature
    max_age:
      hours: 24
    sampling_size: 500
    precision: 1
    name: woonkamer_temperature_stats
  - platform: statistics
    entity_id: sensor.bijkeuken_temperature
    max_age:
      hours: 24
    sampling_size: 500
    precision: 1
    name: bijkeuken_temperature_stats
  - platform: template
    sensors:
      buiten_temp_min:
        value_template: "{{ state_attr('sensor.buiten_temperature_stats', 'min_value') |float(default=0) }}"
        friendly_name: "Minimum buiten temperatuur"
      buiten_temp_max:
        value_template: "{{ state_attr('sensor.buiten_temperature_stats', 'max_value') |float(default=0) }}"
        friendly_name: "Maximum buiten temperatuur"
      zolder_voor_temp_min:
        value_template: "{{ state_attr('sensor.sensor.zolder_voor_temperature_stats', 'min_value') |float(default=0) }}"
        friendly_name: "Minimum temperatuur zolder voor"
      zolder_voor_temp_max:
        value_template: "{{ state_attr('sensor.sensor.zolder_voor_temperature_stats', 'max_value') |float(default=0) }}"
        friendly_name: "Maximum temperatuur zolder voor"
      zolder_achter_temp_min:
        value_template: "{{ state_attr('sensor.zolder_achter_temperature_stats', 'min_value') |float(default=0) }}"
        friendly_name: "Minimum temperatuur zolder achter"
      zolder_achter_temp_max:
        value_template: "{{ state_attr('sensor.zolder_achter_temperature_stats', 'max_value') |float(default=0) }}"
        friendly_name: "Maximum temperatuur zolder achter"
      studeerkamer_temp_min:
        value_template: "{{ state_attr('sensor.studeerkamer_temperature_stats', 'min_value') |float(default=0) }}"
        friendly_name: "Minimum temperatuur studeerkamer"
      studeerkamer_temp_max:
        value_template: "{{ state_attr('sensor.studeerkamer_temperature_stats', 'max_value') |float(default=0) }}"
        friendly_name: "Maximum temperatuur studeerkamer"
      slaapkamer_temp_min:
        value_template: "{{ state_attr('sensor.buiten_temperature_stats', 'min_value') |float(default=0) }}"
        friendly_name: "Minimum temperatuur slaapkamer"
      slaapkamer_temp_max:
        value_template: "{{ state_attr('sensor.buiten_temperature_stats', 'max_value') |float(default=0) }}"
        friendly_name: "Maximum temperatuur slaapkamer"
      badkamer_temp_min:
        value_template: "{{ state_attr('sensor.badkamer_temperature_stats', 'min_value') |float(default=0) }}"
        friendly_name: "Minimum temperatuur badkamer"
      badkamer_temp_max:
        value_template: "{{ state_attr('sensor.badkamer_temperature_stats', 'max_value') |float(default=0) }}"
        friendly_name: "Maximum temperatuur badkamer"
      woonkamer_temp_min:
        value_template: "{{ state_attr('sensor.woonkamer_temperature_stats', 'min_value') |float(default=0) }}"
        friendly_name: "Minimum temperatuur woonkamer"
      woonkamer_temp_max:
        value_template: "{{ state_attr('sensor.woonkamer_temperature_stats', 'max_value') |float(default=0) }}"
        friendly_name: "Maximum temperatuur woonkamer"
      bijkeuken_temp_min:
        value_template: "{{ state_attr('sensor.bijkeuken_temperature_stats', 'min_value') |float(default=0) }}"
        friendly_name: "Minimum temperatuur bijkeuken"
      bijkeuken_temp_max:
        value_template: "{{ state_attr('sensor.bijkeuken_temperature_stats', 'max_value') |float(default=0) }}"
        friendly_name: "Maximum temperatuur bijkeuken"

automation:
  - alias: "kopieer forecast naar input_number"
    id: "8749832079108927490821"
    trigger:
      - platform: time
        at: "00:00:01"
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.berkhout_temperatuur_0d
        data:
          value: "{{ states('sensor.berkhout_temperature_1d') }}"
  - alias: "alert zolder ramen dicht"
    trigger:
      platform: template
      value_template: "{{ ([states('sensor.zolder_voor_temperature'), states('sensor.zolder_achter_temperature')]|min|float -1) < (states('sensor.buiten_temperature')|float)}} "
    action:
      - service: tts.google_say
        target:
          entity_id: media_player.speakers
        data:
          message: "Tijd om de ramen op zolder dicht te doen"
          language: "nl"
      - service: automation.turn_on
        target:
          entity_id: automation.alert_zolder_ramen_open
      - service: automation.turn_off
        target:
          entity_id: automation.alert_zolder_ramen_dicht
  - alias: "alert verdieping ramen dicht"
    trigger:
      platform: template
      value_template: "{{ ([states('sensor.studeerkamer_temperature'), states('sensor.buiten_temperature'), states('sensor.badkamer_temperature')]|min|float -1) < (states('sensor.buiten_temperature')|float)}} "
    action:
      - service: tts.google_say
        target:
          entity_id: media_player.speakers
        data:
          message: "Tijd om de ramen op de eerste verdieping dicht te doen"
          language: "nl"
      - service: automation.turn_on
        target:
          entity_id: automation.alert_verdieping_ramen_open
      - service: automation.turn_off
        target:
          entity_id: automation.alert_verdieping_ramen_dicht

  - alias: "alert beneden ramen dicht"
    trigger:
      platform: template
      value_template: "{{ (states('sensor.woonkamer_temperature')|float -1) < (states('sensor.buiten_temperature')|float)}} "
    action:
      - service: tts.google_say
        target:
          entity_id: media_player.speakers
        data:
          message: "Tijd om de ramen beneden dicht te doen"
          language: "nl"
      - service: automation.turn_on
        target:
          entity_id: automation.alert_beneden_ramen_open
      - service: automation.turn_off
        target:
          entity_id: automation.alert_beneden_ramen_dicht

  - alias: "alert zolder ramen open"
    trigger:
      platform: template
      value_template: "{{ ([states('sensor.zolder_voor_temperature'), states('sensor.zolder_achter_temperature')]|min|float -1) > (states('sensor.buiten_temperature')|float)}} "
    action:
      - service: tts.google_say
        target:
          entity_id: media_player.speakers
        data:
          message: "Tijd om de ramen op zolder open te doen"
          language: "nl"
      - service: automation.turn_on
        target:
          entity_id: automation.alert_zolder_ramen_dicht
      - service: automation.turn_off
        target:
          entity_id: automation.alert_zolder_ramen_open

  - alias: "alert verdieping ramen open"
    trigger:
      platform: template
      value_template: "{{ ([states('sensor.studeerkamer_temperature'), states('sensor.buiten_temperature'), states('sensor.badkamer_temperature')]|min|float -1) > (states('sensor.buiten_temperature')|float)}} "
    action:
      - service: tts.google_say
        target:
          entity_id: media_player.speakers
        data:
          message: "Tijd om de ramen op de eerste verdieping open te doen"
          language: "nl"
      - service: automation.turn_on
        target:
          entity_id: automation.alert_verdieping_ramen_dicht
      - service: automation.turn_off
        target:
          entity_id: automation.alert_verdieping_ramen_open
  - alias: "alert beneden ramen open"
    trigger:
      platform: template
      value_template: "{{ (states('sensor.woonkamer_temperature')|float -1) > (states('sensor.buiten_temperature')|float)}} "
    action:
      - service: tts.google_say
        target:
          entity_id: media_player.speakers
        data:
          message: "Tijd om de ramen beneden open te doen"
          language: "nl"
      - service: automation.turn_on
        target:
          entity_id: automation.alert_beneden_ramen_dicht
      - service: automation.turn_off
        target:
          entity_id: automation.alert_beneden_ramen_open
